(function(g){var window=this;'use strict';var s2A=function(h){h.style.set(4);h.X=h.text;h.X.style=h.style;h.U.mode=1<<h.X.Y},pC1=function(h,c){var t=new g.Fx;
t.languageCode=h.languageCode;t.languageName=h.languageName;t.name=h.name;t.displayName=h.displayName;t.kind=h.kind;t.isDefault=!1;t.X=h.X;t.isTranslateable=h.isTranslateable;t.vssId=h.vssId;t.url=h.url;t.translationLanguage=c;h.xtags&&(t.xtags=h.xtags);h.captionId&&(t.captionId=h.captionId);return t},GH=function(h,c){h=kN(h,c);
return h!==void 0?h:null},u7I=function(h,c){if(!g.WTU(h)||h.X!=null&&g.zL(c,h.X)&&h.X.X.rawcc!=null)return!1;
c=!!h.X&&h.X.isManifestless&&Object.values(h.X.X).some(function(t){return g.iP(t,"386")});
h=!!h.X&&!h.X.isManifestless&&g.X49(h.X);return c||h},qhs=function(h,c){return c?h.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},DX=function(h,c){g.TI.call(this,c);
this.X=h;this.Z=c;this.logger=new g.G7("caps");this.Y=this.C=null;this.j=new gss(this.Z,this,this.logger,this.X.Hr)},j2p=function(h,c,t){t=t===void 0?!1:t;
var p=md.XY;h.U={};Object.assign(h.U,md);h.U.XY={};Object.assign(h.U.XY,p);h.C={XY:{}};var u=c.backgroundOverride?h.C:h.U,q=c.background||p.background;fL.test(q);u.XY.background=q;u=c.colorOverride?h.C:h.U;q=c.color||p.color;fL.test(q);u.XY.color=q;u=c.windowColorOverride?h.C:h.U;q=c.windowColor||md.windowColor;fL.test(q);u.windowColor=q;u=c.backgroundOpacityOverride?h.C:h.U;q=c.backgroundOpacity;q==null&&(q=p.backgroundOpacity);u.XY.backgroundOpacity=q;u=c.fontSizeIncrementOverride?h.C:h.U;q=c.fontSizeIncrement;
q==null&&(q=p.fontSizeIncrement);u.XY.fontSizeIncrement=q;q=c.fontStyleOverride?h.C:h.U;u=c.fontStyle;u==null&&(u=p.bold&&p.italic?3:p.bold?1:p.italic?2:0);q=q.XY;switch(u){case 1:q.bold=!0;delete q.italic;break;case 2:delete q.bold;q.italic=!0;break;case 3:q.bold=!0;q.italic=!0;break;default:delete q.bold,delete q.italic}u=c.textOpacityOverride?h.C:h.U;q=c.textOpacity;q==null&&(q=p.textOpacity);u.XY.textOpacity=q;u=c.windowOpacityOverride?h.C:h.U;q=c.windowOpacity;q==null&&(q=md.windowOpacity);u.windowOpacity=
q;u=c.charEdgeStyleOverride?h.C:h.U;q=c.charEdgeStyle;q==null&&(q=p.charEdgeStyle);u.XY.charEdgeStyle=q;u=c.fontFamilyOverride?h.C:h.U;q=c.fontFamily;q==null&&(q=p.fontFamily);u.XY.fontFamily=q;h.loaded&&h.yr();t&&g.Ov("yt-player-caption-display-settings",c,2592E3)},b3y=function(h){if(h.K.IF===1||h.videoData.VW===1||g.qh(h.videoData,"yt:cc")==="alwayson")return!0;
if(h.videoData.captionTracks.length)var c=h.getAudioTrack().B;if(h.K.IF===2){if(g.oN(h.K))var t=IMT(h);else if(h.storage)try{t=h.storage.get("module-enabled")}catch(u){h.storage.remove("module-enabled")}else t=null;if(t!=null)return!!t}t=qhs(h.player.getAudioTrack(),g.oN(h.K));var p=g.qh(h.videoData,"yt:cc");if(Yhr(h)===void 0){if(t==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return p?p==="on":!0;if(t==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return p==="on"}else return p==="on";return c==="ON"||g.qh(h.videoData,
"yt:cc")==="on"},kme=function(h,c){if(c instanceof RU){var t=h.q2[c.id];
t&&t.B!==c&&(t.dispose(),delete h.q2[c.id],t=null);t||(t=CIp(h,c))&&(h.q2[c.id]=t)}else t=c.windowId,h.AS[t]||(h.AS[t]=[]),h.AS[t].push(c)},Gme=function(h){var c=h.split(":");
h=0;c=g.H(c);for(var t=c.next();!t.done;t=c.next())h=h*60+Number(t.value);return h*1E3},J4=function(h){var c=h.byteOffset;
h.byteOffset+=4;return h.X.getUint32(c)},Dq6=function(h,c){g.hO(h.videoData)&&(c=!0);
c||(c=h.Y==="TTS"?!1:h.Y==="INNERTUBE"?!1:!0);return c||h.K.L("web_deprecate_always_includes_asr_setting")&&g.oN(h.K)?!0:!!g.V_().JU(66)},fMR=function(h,c,t){mqT(h,c).then(function(p){p&&t(p.trackData,new g.Fx(p.metadata))})},Rd1=function(h,c,t){g.l(function(p){h.X=g.i$(c,t);
g.bZ(p)})},Nz=function(h,c){if(!h.X)return null;
if(h.M2&&h.M2.Y)return h.M2.Y;c=Dq6(h,c);c=g.KK(h.X.B,c);var t=null;if(JNq(h.K)){var p=h.Z.isInline()?void 0:g.j5("yt-player-caption-sticky-language");for(var u=[p,h.videoData.captionsLanguagePreference,h.K.captionsLanguagePreference,g.qh(h.videoData,"yt:cc_default_lang")],q=!1,I=0;I<u.length;I++){var b=u[I];if(b){q=!0;for(var C=0;C<c.length;C++)if(g.pZ(c[C])===b)return c[C];for(C=0;C<c.length;C++)if(g.pZ(c[C]).split("-")[0]===b.split("-")[0])return c[C]}}if(q&&h.X&&(u=h.X.T,u.length))for(u=g.H(u),
q=u.next();!q.done;q=u.next())if(q=q.value,q.languageCode===p){t=q;break}}else for(p=[h.videoData.captionsLanguagePreference,h.K.captionsLanguagePreference,g.qh(h.videoData,"yt:cc_default_lang")],u=0;u<p.length;u++)for(q=0;q<c.length;q++)if(g.pZ(c[q])===p[u])return c[q];p=null;h.M2&&h.M2.U&&(p=h.M2.U);p||(p=c.find(function(k){return k.isDefault})||null);
p||(p=c[0]||lL(h));p&&t&&g.pZ(p).split("-")[0]!==t.languageCode.split("-")[0]&&(p=pC1(p,t));return p},lMs=function(h,c){var t=h.Z.Vl().Ig().textTracks;
h=h.B.toString();for(var p=0;p<t.length;p++){var u=t[p];u.id===h&&(c?u.mode!=="showing"&&(u.mode="showing"):u.mode==="showing"&&(u.mode="disabled"))}},XCs=function(h,c){var t={},p=c.background?c.background:h.X.XY.background;
if(c.backgroundOpacity!=null||c.background){var u=c.backgroundOpacity!=null?c.backgroundOpacity:h.X.XY.backgroundOpacity;p=NGA(p);t.background="rgba("+p[0]+","+p[1]+","+p[2]+","+u+")";h.mf&&(t["box-decoration-break"]="clone",t["border-radius"]=h.AS/8+"px")}if(c.fontSizeIncrement!=null||c.offset!=null)t["font-size"]=h.GM*TGm(c)+"px";p=1;u=c.color||h.X.XY.color;if(c.color||c.textOpacity!=null)u=NGA(u),p=c.textOpacity==null?h.X.XY.textOpacity:c.textOpacity,u="rgba("+u[0]+","+u[1]+","+u[2]+","+p+")",
t.color=u,t.fill=u;var q=c.charEdgeStyle;q===0&&(q=void 0);if(q){u="rgba(34, 34, 34, "+p+")";var I="rgba(204, 204, 204, "+p+")";c.M3&&(I=u=c.M3);var b=h.GM/16/2,C=Math.max(b,1),k=Math.max(2*b,1),G=Math.max(3*b,1),D=Math.max(5*b,1);p=[];switch(q){case 4:for(;G<=D;G+=b)p.push(k+"px "+k+"px "+G+"px "+u);break;case 1:k=window.devicePixelRatio>=2?.5:1;for(q=C;q<=G;q+=k)p.push(q+"px "+q+"px "+u);break;case 2:p.push(C+"px "+C+"px "+I);p.push("-"+C+"px -"+C+"px "+u);break;case 3:for(G=0;G<5;G++)p.push("0 0 "+
k+"px "+u)}t["text-shadow"]=p.join(", ")}u="";switch(c.fontFamily){case 1:u='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:u='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:u='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:u='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:u='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:u=g.I8()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:u='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}u&&(t["font-family"]=u);u=c.offset;u==null&&(u=h.X.XY.offset);switch(u){case 0:t["vertical-align"]="sub";break;case 2:t["vertical-align"]="super"}c.fontFamily===7&&(t["font-variant"]="small-caps");c.bold&&(t["font-weight"]="bold");c.italic&&(t["font-style"]="italic");c.underline&&(t["text-decoration"]=
"underline");c.E5&&(t.visibility="hidden");c.gG===1&&h.U&&(t["text-combine-upright"]="all",t["text-orientation"]="mixed",u=g.Uq||g.kV,h.B.params.xT===3?t.transform=u?"rotate(90deg)":"rotate(180deg)":u&&(t.transform="rotate(-90deg)"));if(c.textEmphasis===1||c.textEmphasis===2||c.textEmphasis===3||c.textEmphasis===4||c.textEmphasis===5)if(g.Uq)t["font-weight"]="bold";else switch(t["text-emphasis-style"]="filled circle",t["text-emphasis-color"]="currentcolor",t["webkit-text-emphasis"]="filled circle",
c.textEmphasis){case 4:case 3:t["text-emphasis-position"]="under left";t["webkit-text-emphasis-position"]="under left";break;case 5:case 2:t["text-emphasis-position"]="over right",t["webkit-text-emphasis-position"]="over right"}return t},i3p=function(h){if(!(h.byteOffset<h.X.byteLength)||J4(h)!==1380139777)return!1;
h.version=TH(h);if(h.version>1)return!1;TH(h);TH(h);TH(h);return!0},Wom=function(h,c,t,p){var u=c/360*16;
c>=h&&(h=640,p>t*1.3&&(h=480),u=t/h*16);return u},lL=function(h){return h.M2&&h.M2.X},Uqz=function(){var h=void 0;
h=h===void 0?{}:h;var c="suggest_correction"in g.Kvq?g.Kvq.suggest_correction:"Edit caption";c=c||"";var t={},p;for(p in h){t={Cm:t.Cm};t.Cm=p;var u=function(q){return function(){return String(h[q.Cm])}}(t);
c=c.replace(new RegExp("\\$\\{"+t.Cm+"\\}","gi"),u);c=c.replace(new RegExp("\\$"+t.Cm,"gi"),u)}return c},XY=function(){this.type=0},rNq=function(h){this.X=h;
this.T=0;this.U=new O3y(this.X);this.C=new O3y(this.X);this.B=new iL;this.Y=this.U},Kos=function(h,c,t,p,u,q){g.v.call(this);
this.policy=h;this.player=c;this.r9=t;this.J=p;this.T=u;this.M2=q;this.Y=new W$;this.C=-1;this.B=this.U=this.X=null;this.XM=0;this.j=new g.SF(this.f1,1E3,this);this.events=new g.dD(this);g.Z(this,this.j);g.Z(this,this.events);this.events.S(c,"SEEK_COMPLETE",this.TC);this.TC();this.f1()},osz=function(h,c){var t={},p=c.getAttribute("wp");
p&&Object.assign(t,h.J[p]);h=GH(c,"ap");h!=null&&(t.oM=h);h=kN(c,"cc");h!=null&&(t.Y5=h);h=kN(c,"ah");h!=null&&(t.AZ=h);h=kN(c,"rc");h!=null&&(t.Zb=h);c=kN(c,"av");c!=null&&(t.Tm=c);return t},zds=function(h,c){return c!=null&&c in h.X.X?h.X.X[c]:null},wCz=function(h,c){var t=[],p;
for(p in h.X.X)if(h.X.X.hasOwnProperty(p)){var u=h.X.X[p];if(g.iP(u,c||null)){var q=u.info.id,I=q,b="."+q,C="",k="";if(u=u.info.captionTrack)q=u.languageCode,I=u.displayName,b=u.vssId,C=u.kind,k=u.id;t.push(new g.Fx({id:p,languageCode:q,languageName:I,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:b,kind:C,captionId:k}))}}return t},Q2z=function(h,c,t,p,u,q,I){var b=q[0],C=I[b.getAttribute("p")];
if(C.h$===1){var k=q[1],G=q[2];q=q[3];b.getAttribute("t");k.getAttribute("t");G.getAttribute("t");q.getAttribute("t");b.getAttribute("p");k.getAttribute("p");q.getAttribute("p");I=I[G.getAttribute("p")];b=H36(b.textContent,k.textContent,G.textContent,q.textContent,I);return new U6(h,c,u,t,b,p,C)}switch(C.h$){case 9:case 10:C.textEmphasis=1;break;case 11:C.textEmphasis=2;break;case 12:C.textEmphasis=3;break;case 13:C.textEmphasis=4;break;case 14:C.textEmphasis=5}return new U6(h,c,u,t,b.textContent||
"",p,C)},JNq=function(h){return g.oN(h)||h.L("web_enable_caption_language_preference_stickiness")},NGA=function(h){if(!PI6.test(h))throw Error("'"+h+"' is not a valid hex color");
h.length==4&&(h=h.replace(AN6,"#$1$1$2$2$3$3"));h=h.toLowerCase();h=parseInt(h.slice(1),16);return[h>>16,h>>8&255,h&255]},dqI=function(h){var c,t=!((c=h.Z.Vl())==null||!c.VR());
return h.bB&&t&&h.Y!=="LIVE"&&h.Y!=="SABR_LIVE"},O6=function(h,c,t,p,u,q,I,b,C,k){var G=k.isInline()&&!0,D={};
Object.assign(D,c);Object.assign(D,h.params);Object.assign(D,t);var m={};Object.assign(m,c.XY);h.params.XY&&Object.assign(m,h.params.XY);Object.assign(m,t.XY);G&&(D.windowOpacity=.6,m.backgroundOpacity=0);D.XY=m;var f=D.xT===1,R=[{D:"span",G:"captions-text",W:{style:"word-wrap: normal; display: block;"}}],X,O,w;(b=b.V3("caption_edit_on_hover")&&((X=k.getVideoData().getPlayerResponse())==null?void 0:(O=X.captions)==null?void 0:(w=O.playerCaptionsTracklistRenderer)==null?void 0:w.openTranscriptCommand))&&
R.unshift({D:"button",G:"caption-edit",W:{tabindex:"0","aria-label":Uqz()},V:[{D:"svg",W:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},V:[{D:"path",W:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.Q.call(this,{D:"div",G:"caption-window",W:{id:"caption-window-"+h.id,dir:f?"rtl":"ltr",tabindex:"0",lang:D.lang},V:R});var z=
this;this.C=[];this.hS=!1;this.B=h;this.y3=this.mS=null;this.Fs=q;this.dF=I;this.j=null;this.maxWidth=q*.96;this.maxHeight=I*.96;this.X=D;this.f2=t;this.XM=c;this.Y=this.Yk("captions-text");this.mf=this.Y.style.getPropertyValue("box-decoration-break")!==""||this.Y.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.GM=Wom(p,u,q,I);this.Af=C;b&&(this.T=this.Yk("caption-edit"),this.S(this.T,"click",function(){z.Af()}));
this.type=0;this.AS=this.GM*TGm(m);this.Pr=G;h=new g.Aw(this.element,!0);g.Z(this,h);h.subscribe("dragstart",this.qS,this);h.subscribe("dragmove",this.Uo,this);h.subscribe("dragend",this.F7,this);this.eb=this.bB=this.g9=this.N2=0;h="";this.X.windowOpacity&&(h=NGA(this.X.windowColor),h="rgba("+h[0]+","+h[1]+","+h[2]+","+this.X.windowOpacity+")");c={"background-color":h,display:this.X.isVisible===!1?"none":"","text-align":aMs[this.X.textAlign]};this.mf&&(c["border-radius"]=h?this.AS/8+"px":"");(this.U=
this.B.params.xT===2||this.B.params.xT===3)&&Z3z(this,this.element);g.wI(this.element,c);if(G){var P;(P=this.element.parentElement)==null||P.style.setProperty("--caption-window-color",h)}switch(this.X.oM){case 0:case 1:case 2:g.iq(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.iq(this.element,"ytp-caption-window-bottom")}},rV=function(h,c){g.TI.call(this,c);
this.X=h;this.Z=c;this.Y=null;this.C=!1;this.logger=new g.G7("caps");this.j=g.zL(this.Z,this.X)},KL=function(h,c){h.Z.isInline()||g.Ov("yt-player-sticky-caption",c,2592E3)},oU=function(h){var c=lL(h);
return!!c&&h.B===c},vse=function(h,c){if(!c)return"";
h.U&&h.B.params.rE!==1&&(c*=-1);return"translate"+(h.U?"X":"Y")+"("+c+"px)"},wV=function(h){zH.call(this);
this.C=h;this.X=new Map;this.Y=new Map;this.T=new Map;this.B=new Map},zH=function(){g.v.apply(this,arguments)},xqz=function(h,c,t){var p=[],u;
for(u in h.X.X)if(h.X.X.hasOwnProperty(u)){var q=h.X.X[u];if(g.iP(q,t||null)){var I=q.info.captionTrack;I&&I.languageCode===c&&p.push(q)}}return p.length?p[0]:null},Shs=function(h,c){var t={},p=c.getAttribute("ws");
Object.assign(t,p?h.M2[p]:h.Y);h=GH(c,"mh");h!=null&&(t.MJ=h);h=GH(c,"ju");h!=null&&(t.textAlign=h);h=GH(c,"pd");h!=null&&(t.xT=h);h=GH(c,"sd");h!=null&&(t.rE=h);h=H$(c,"wfc");h!=null&&(t.windowColor=h);c=kN(c,"wfo");c!==void 0&&(t.windowOpacity=c/255);return t},yNs=function(h,c,t){c&&!h.r9?(c=ns1({xT:0,
lang:"fr"}),h.r9=[c,new U6(c.start,c.end-c.start,0,c.id,t!=null?t:"Aper\u00e7u des sous-titres")],h.player.bX(h.r9)):!c&&h.r9&&(eds(h,h.r9),h.r9=null)},M$p=function(h,c,t,p){h.B.update();
c=V$e(c,t,h.B);switch(c.result){case 0:return;case 1:case 2:return}var u=c.X5;t=c.Bi;if(32<=u||!u)h.X.mode&h.X.B&&(c=u,c&128&&(c=127),t&128&&(t=127),h=h.Y.X,c&96&&QB(h,0,c),t&96&&QB(h,0,t),c!==0&&t!==0&&h.style.type===3&&P$(h,p));else if(u&16)a:if(!h.B.matches(u,t)&&(c=h.B,c.X5=u,c.Bi=t,c.state=2,c=u&8?h.C:h.U,h.Y=c,h.X.mode=1<<(h.T<<2)+(c.T<<1)+(c.style.type===4?1:0),(h.X.mode|1<<(h.T<<2)+(c.T<<1)+(c.style.type!==4?1:0))&h.X.B))if(t&64){p=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(u&7)<<1|t>>5&1];
h=t&16?((t&14)>>1)*4:0;t=c.X;switch(c.style.get()){case 4:p=t.row;break;case 3:if(p!==t.row){if(p<t.X&&(p=t.X,p===t.row))break;var q=1+t.row-t.X,I=1+p-t.X;Esp(t,I,q,t.X);c=q;u=t.X;I<q?(q=I+u-q,q>0&&(c+=q,u-=q)):(q=q+u-I,q>0&&(u-=q));A4(t,c,u)}}t.row=p;t.B=h+1}else switch(u&7){case 1:switch(t&112){case 32:QB(c.X,0,32);break a;case 48:t===57?(p=c.X,dV(p).X=0,p.B<32&&p.B++):QB(c.X,1,t&15)}break;case 2:t&32&&QB(c.X,2,t&31);break;case 3:t&32&&QB(c.X,3,t&31);break;case 4:case 5:if(32<=t&&t<=47)switch(t){case 32:Los(c);
break;case 33:p=c.X;p.B>1&&(--p.B,dV(p).X=0);break;case 36:p=c.X;c=dV(p);for(h=0;h<=15;h++)for(t=0;t<=32;t++)if(p.U[h][t]===c){for(;t<=32;t++)p.U[h][t].reset();break}break;case 37:$qs(c,2,p);break;case 38:$qs(c,3,p);break;case 39:$qs(c,4,p);break;case 40:QB(c.X,0,32);break;case 41:c.style.set(2);c.X=c.B;c.X.X=0;c.X.style=c.style;c.U.mode=1<<c.X.Y;break;case 42:p=c.text;p.X=15;p.style.set(4);BGy(p);s2A(c);break;case 43:s2A(c);break;case 44:h=c.B;switch(c.style.get()){case 1:case 2:case 3:P$(h,p)}A4(h,
0,15);break;case 45:b:{h=c.X;switch(c.style.get()){default:case 2:case 1:break b;case 4:if(h.row<15){++h.row;h.B=1;break b}break;case 3:}h.X<2&&(h.X=2,h.row<h.X&&(h.row=h.X));c=h.row-h.X+1;P$(h,p);Esp(h,c,c+1,h.X-1);A4(h,h.row,1)}break;case 46:A4(c.Y,0,15);break;case 47:P$(c.B,p),c.Y.updateTime(c.U.time+0),p=c.Y,c.Y=c.B,c.B=p,Los(c)}break;case 7:switch(t){case 33:case 34:case 35:p=c.X,(p.B+=t&3)>32&&(p.B=32)}}},aU=function(h){this.T=h;
this.U=[];this.X=this.B=this.row=0;this.style=new XY;for(h=this.Y=0;h<=15;h++){this.U[h]=[];for(var c=0;c<=32;c++)this.U[h][c]=new Foq}},ce1=function(h,c){var t=[],p;
for(p in h.X.X)if(h.X.X.hasOwnProperty(p)){var u=h.X.X[p];if(g.iP(u,c||null)){var q=u.info.id,I=q,b="."+q,C="",k="";if(u=u.info.captionTrack)q=u.languageCode,I=u.displayName,b=u.vssId,C=u.kind,k=u.id;else{u=q;var G=g.tis.get(u);G==null&&(G=hJI[u]||hJI[u.replace(/-/g,"_")],g.tis.set(u,G));u=G;I=u||I}t.push(new g.Fx({id:p,languageCode:q,languageName:I,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:b,kind:C,captionId:k}))}}return t},kN=function(h,c){h=h.getAttribute(c);
if(h!=null)return Number(h)},tFq=function(h,c,t,p,u,q,I,b,C){switch(I.tagName){case "b":b.bold=!0;
break;case "i":b.italic=!0;break;case "u":b.underline=!0}for(var k=0;k<I.childNodes.length;k++){var G=I.childNodes[k];if(G.nodeType===3)G=new U6(c,t,p,u.id,G.nodeValue,q||k>0,g.mr(b)?void 0:b),C.push(G),u.X.push(G);else{var D={};Object.assign(D,b);tFq(h,c,t,p,u,!0,G,D,C)}}},W$=function(){this.segments=[]},A4=function(h,c,t){for(var p=0;p<t;p++)for(var u=0;u<=32;u++)h.U[c+p][u].reset()},O3y=function(h){this.U=h;
this.T=0;this.style=new XY;this.C=new aU(this.U);this.j=new aU(this.U);this.text=new aU(this.U);this.B=this.C;this.Y=this.j;this.X=this.B},ns1=function(h){var c="_"+ZX++;
return new RU(0,0x8000000000000,0,c,h)},p01=function(h){var c=seR.length;
if(h.byteLength<c)return!1;h=new Uint8Array(h,0,c);for(var t=0;t<c;t++)if(seR[t]!==h[t])return!1;return!0},P$=function(h,c){if(h.style.type===3){for(var t=0,p=0,u=h.T.time+0,q="",I="",b=u,C=1;C<=15;++C){for(var k=!1,G=p?p:1;G<=32;++G){var D=h.U[C][G];
if(D.X!==0){t===0&&(t=C,p=G);k=String.fromCharCode(D.X);var m=D.timestamp;m<u&&(u=m);D.timestamp=b;I&&(q+=I,I="");q+=k;k=!0}if((D.X===0||G===32)&&k){I="\n";break}else if(p&&!k)break}if(t&&!k)break}q&&c.Y(t,p,u,b,q)}else for(p=t=0,q=u=h.T.time+0,I=1;I<=15;++I)for(b="",C=1;C<=32;++C)if(G=h.U[I][C],D=G.X,D!==0&&(t===0&&(t=I,p=C),k=String.fromCharCode(D),m=G.timestamp,m<=u&&(u=m),b+=k,G.reset()),C===32||D===0)b&&c.Y(t,p,u,q,b),u=q,b="",p=t=0},v$=function(h){h.isActive()||h.start()},ubz=function(h,c,t){var p=
[],u;
for(u in h.X.X)if(h.X.X.hasOwnProperty(u)){var q=h.X.X[u];if(g.iP(q,t||null)){var I=q.info.captionTrack;I&&I.languageCode===c&&p.push(q)}}return p.length?p[0]:null},qks=function(h){h.j=g.Cl("SPAN");
g.wI(h.j,{display:"block"});g.iq(h.j,"caption-visual-line");h.Y.appendChild(h.j)},gzy=function(h){return h.X&&h.X.C?h.X.C+h.player.Jf()<h.player.getCurrentTime():!1},V$e=function(h,c,t){if(h===255&&c===255||!h&&!c)return{X5:h,
Bi:c,result:0};h=jeq[h];c=jeq[c];if(h&128){var p;if(p=!(c&128))p=c,p=t.Cr()&&t.Bi===p;if(p)return{X5:h,Bi:c,result:1}}else if(c&128&&1<=h&&h<=31)return{X5:h,Bi:c,result:2};return{X5:h,Bi:c,result:3}},Yks=function(h,c){h.X.sort(function(u,q){var I=u.time-q.time;
return I===0?u.order-q.order:I});
for(var t=g.H(h.X),p=t.next();!p.done;p=t.next())p=p.value,h.time=p.time,p.type===0?I4s(h,p.EF,p.nt,c):p.type===1&&h.B&496&&M$p(h.T,p.EF,p.nt,c);h.X.length=0},b5I=function(h,c){h=g.cp(h,{startTimeMs:c},function(t,p){return t.startTimeMs-p.startTimeMs});
return h>=0?h:-h-2},xN=function(h){h=h.split("px");
return h.length>0?(h=Number(h[0]))?h:0:0},C0q=function(h,c,t){var p=g.QJ(h,0,1836476516),u=9E4;
p&&(u=g.$O(p)||9E4);p=0;for(var q=g.S1(h,1836019558),I=0;I<q.length;I++){var b=q[I];I<c.length&&(b=g.QJ(h,b.dataOffset,1953653094))&&(b=g.QJ(h,b.dataOffset,1952867444))&&(b=g.FCo(b)/u*1E3,I===0&&(p=b),c[I].sB=b-p+t||t*I*1E3)}},Foq=function(){this.timestamp=this.X=0},IMT=function(h){if(!h.Z.isInline())return g.j5("yt-player-sticky-caption")},RU=function(h,c,t,p,u){g.et.call(this,h,h+c,{priority:t,
namespace:"captions"});this.id=p;this.params=u;this.X=[]},Gup=function(h,c){kuq(h);
var t=h.q2.reduce(function(q,I){return(h.U?I.offsetWidth:I.offsetHeight)+q},0);
t=h.J-t;if(t!==h.ZM){var p=t>0&&h.ZM===0,u=t<h.ZM;c||isNaN(t)||p||!u||(g.iq(h.element,"ytp-rollup-mode"),h.S(h.element,"transitionend",h.s_));g.wI(h.Y,"transform",vse(h,t));h.ZM=t}kuq(h)},H36=function(h,c,t,p,u){var q=g.I8(),I=q?g.Cl("DIV"):g.Cl("RUBY"),b=g.Cl("SPAN");
b.textContent=h;I.appendChild(b);h=q?g.Cl("DIV"):g.Cl("RP");h.textContent=c;I.appendChild(h);c=q?g.Cl("DIV"):g.Cl("RT");c.textContent=t;I.appendChild(c);t=u.h$;if(t===10||t===11||t===12||t===13||t===14)if(g.wI(c,"text-emphasis-style","filled circle"),g.wI(c,"text-emphasis-color","currentcolor"),g.wI(c,"webkit-text-emphasis","filled circle"),u.h$===11||u.h$===13)g.wI(c,"webkit-text-emphasis-position","under left"),g.wI(c,"text-emphasis-position","under left");t=!0;if(u.h$===4||u.h$===7||u.h$===12||
u.h$===14)g.wI(I,"ruby-position","over"),g.wI(I,"-webkit-ruby-position","before");else if(u.h$===5||u.h$===6||u.h$===11||u.h$===13)g.wI(I,"ruby-position","under"),g.wI(I,"-webkit-ruby-position","after"),t=!1;u=q?g.Cl("DIV"):g.Cl("RP");u.textContent=p;I.appendChild(u);q&&(p=t,g.wI(I,{display:"inline-block",position:"relative"}),q=I.firstElementChild.nextElementSibling,g.wI(q,"display","none"),q=q.nextElementSibling,g.wI(q,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.wI(I.lastElementChild,"display","none"),p?(g.wI(I,"padding-top","0.6em"),g.wI(q,"top","0")):(g.wI(I,"padding-bottom","0.6em"),g.wI(q,"bottom","0")));return I},QB=function(h,c,t){c>=2&&h.B>1&&(--h.B,dV(h).X=0);
var p=dV(h);p.timestamp=h.T.time+0;p.X=DVr(c,t);h.B<32&&h.B++},Z3z=function(h,c){var t="vertical-rl";
h.X.rE===1&&(t="vertical-lr");g.bn&&(t=t==="vertical-lr"?"tb-lr":"tb-rl");g.wI(c,"-o-writing-mode",t);g.wI(c,"-webkit-writing-mode",t);g.wI(c,"writing-mode",t);g.wI(c,"text-orientation","upright");g.iq(c,"ytp-vertical-caption");h.B.params.xT===3&&(g.wI(c,"text-orientation",""),g.wI(c,"transform","rotate(180deg)"))},kuq=function(h){h.q2=Array.from(h.element.getElementsByClassName("caption-visual-line"));
for(var c=h.B.params.Zb,t=0,p=0,u=h.q2.length-1;t<c&&u>-1;){var q=h.q2[u];p+=h.U?q.offsetWidth:q.offsetHeight;t++;u--}h.J=p;c=Math;t=c.max;isNaN(h.uB)&&((p=h.X.Y5)?(u=g.Cl("SPAN"),g.sp(u,"\u2013".repeat(p)),g.wI(u,XCs(h,h.X.XY)),h.Y.appendChild(u),h.uB=u.offsetWidth,h.Y.removeChild(u)):h.uB=0);p=h.Y;h.r9=t.call(c,h.uB,h.Xu,(h.U?p.offsetHeight:p.offsetWidth)+1)},S2=function(h){zH.call(this);
this.Y=h;this.pens={};this.J={};this.M2={};this.T="_"+ZX++;this.j={};this.B=this.X=null;this.C=!0},mVs=function(){},dV=function(h){return h.U[h.row][h.B]},RJ6=function(h,c,t){if(typeof c==="string"||f4T(c))return[{trackData:c,
sB:t}];if(typeof c==="string"&&c.substring(0,6)==="WEBVTT"||typeof c!=="string"&&p01(c))return[{trackData:c,sB:t}];var p=new DataView(c);if(p.byteLength<=8||p.getUint32(4)!==1718909296)return[];var u=g.uTZ(p);if(h.B&&u){var q=g.EfB(u),I=g.L1i(u);u=u.xB;q&&u&&h.B.kh(u,q,I)}h=g.S1(p,1835295092);if(!h||!h.length||!h[0].size)return[];q=[];for(I=0;I<h.length;I++)u=h[I],u=new Uint8Array(c,u.dataOffset,u.size-(u.dataOffset-u.offset)),u=g.sL(u),q.push({trackData:u,sB:t+I*1E3});C0q(p,q,t);return q=q.filter(function(b){return!!b.trackData})},
Esp=function(h,c,t,p){for(var u=0;u<p;u++)for(var q=0;q<=32;q++){var I=h.U[c+u][q],b=h.U[t+u][q];
I.X=b.X;I.timestamp=b.timestamp}},yB=function(h,c,t){h.loaded&&h.unload();
t!=null&&(h.J=t,h.J&&(g.oN(h.K)?KL(h,!!c):nL(h,!!c)));c!==null||e2(h,!0)||h.P8(c,!!c,h.J?"m":"s");h.B=c;e2(h)&&(h.B=lL(h));var p;JeR(h,(p=h.B)!=null?p:void 0);h.load()},l4e=function(h,c){var t=g.cp(h.segments,c);
t>=0||t<0&&(-t-1)%2===1||(t=-t-1,t>0&&c-h.segments[t-1]===1&&t<h.segments.length&&h.segments[t]-c===1?(g.gL(h.segments,t),g.gL(h.segments,t-1)):t>0&&c-h.segments[t-1]===1?h.segments[t-1]=c:t<h.segments.length&&h.segments[t]-c===1?h.segments[t]=c:(g.NF(h.segments,t,0,c),g.NF(h.segments,t+1,0,c)))},Tcz=function(h){g.dy.call(this,h);
var c=this;this.Z=h;this.mS=[];this.q2={};this.AS={};this.J=!1;this.Y="NONE";this.X=this.M2=this.r9=this.GM=this.N2=null;this.Br={KN:function(){c.KN()},
tP:function(q,I,b,C){c.tP(q,I,b,C)}};
this.B=null;this.K=this.Z.N();this.videoData=this.Z.getVideoData();this.g9=this.Z.vt();this.U={XY:{}};this.C={XY:{}};g.la(this.videoData)?this.Y="OFFLINE":u7I(this.videoData,this.Z)?this.Y="SABR_LIVE":g.fbB(this.videoData,this.Z)?this.Y="LIVE":this.videoData.captionTracks.length?this.Y="INNERTUBE":this.videoData.TW&&(this.Y="TTS");this.bB=this.K.controlsType==="3";this.eb=new VB(this.Z,this.K);this.hS=new g.dD(this);this.j=new g.Q({D:"div",G:"ytp-caption-window-container",W:{id:"ytp-caption-window-container"}});
this.XM={top:0,right:0,bottom:0,left:0,width:1,height:1};var t=null,p=g.zc("yt-html5-player-modules::subtitlesModuleData");p&&(t=new g.Kd(p));this.storage=t;var u;this.Pr=!((u=h.Vl())==null||!u.vZ());this.T=dqI(this);this.uB=!this.T&&this.bB&&this.Pr&&(this.Y==="LIVE"||this.Y==="SABR_LIVE");g.Z(this,this.eb);this.T?this.ZM=this.y3=null:(this.y3=new g.Cy(this.JV,void 0,this),g.Z(this,this.y3),this.ZM=new g.SF(this.Qik,2E3,this),g.Z(this,this.ZM));g.Z(this,this.hS);g.z1(this.player,this.j.element,4);
g.Z(this,this.j);this.T||this.hS.S(h,"resize",this.yr);(this.Xu=g.PX(this.K)&&!g.$r()&&!this.Z.isFullscreen()&&!this.T&&!this.uB)&&this.hS.S(h,"resize",this.MCM);this.hS.S(h,"onPlaybackAudioChange",this.uuM);this.hS.S(h,g.GD("captions"),function(q){c.onCueRangeEnter(q)});
this.hS.S(h,g.tL("captions"),function(q){c.onCueRangeExit(q)});
j2p(this,Ncy()||{});this.player.F3("onCaptionsModuleAvailable")},X0I=function(h,c){if(!h.X)return{};
if(c){g.mr(c)||h.My(c.vss_id,"m");if(h.T||!g.U4(c))return;if(g.mr(c)){yB(h,null,!0);return}for(var t,p=g.KK(h.X.B,!0),u=0;u<p.length;u++){var q=p[u];q.languageCode!==c.languageCode||t&&(q.languageName!==c.languageName||(q.captionId||"")!==(c.captionId||"")||g.ai(q)!==c.displayName)||(t=c.translationLanguage?pC1(q,c.translationLanguage):q)}h.OB(c.position);!t||t===h.B&&h.loaded||(c=g.Ns(),p=g.pZ(t),c.length&&p===c[c.length-1]||(c.push(p),g.Ov("yt-player-caption-language-preferences",c)),JNq(h.K)&&
!h.Z.isInline()&&g.Ov("yt-player-caption-sticky-language",p,2592E3),yB(h,t,!0))}else return h.loaded&&h.B&&!oU(h)?g.Bo(h.B):{};return""},i5m=function(h,c){h.X=function(t,p){if(t.info.Y){var u=t;
if(h.cO.length>0){for(u=h.cO.shift();h.cO.length>0;)u=g.M3(u,h.cO.shift());u=g.M3(u,t)}if(u){t=u;try{var q=g.DF(t)*1E3}catch(k){q=t.info.startTime*1E3}try{var I=g.cGe(t)*1E3}catch(k){I=t.info.duration*1E3}if(q<0||I<0)q<0&&(q=t.info.startTime*1E3),I<0&&(I=t.info.duration*1E3);t.info.startTime=q/1E3;t.info.T=q/1E3;t.info.duration=I/1E3;t.info.J=I/1E3;q=h.NN(u);I=q.O8;q={formatId:q.formatId,startTimeMs:q.startTimeMs,durationMs:q.durationMs,m1:I,Fh:I};I=b5I(h.Uf,q.startTimeMs);var b=(t=I>=0?h.Uf[I]:null)?
t.startTimeMs+t.durationMs:0,C=q.startTimeMs+q.durationMs;!t||q.startTimeMs-b>h.B?h.Uf.splice(I+1,0,q):(t.durationMs=Math.max(b,C)-t.startTimeMs,t.Fh=Math.max(t.Fh,q.Fh));p(h.Uf);q=g.ZJ(u);p=h.U;q=q.buffer.slice(q.byteOffset,q.byteLength+q.byteOffset);u=u.info.T;p.C?p.Y==null?g.B5(p.logger,350058965,"Null loaded track meta data at captions data received"):c.tP(q,p.Y,u*1E3):g.B5(p.logger,350058965,"Null Representation at captions data received")}else g.B5(h.logger,350058965,"Empty slice")}else h.cO.push(t)};
h.Z.addEventListener("sabrCaptionsDataLoaded",h.X)},WHs=function(h,c){var t=g.Cl("SPAN");
g.wI(t,{display:"inline-block","white-space":"pre-wrap"});g.wI(t,XCs(h,c));t.classList.add("ytp-caption-segment");h.j.appendChild(t);t.previousElementSibling&&(g.wI(t.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.wI(t,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return t},UV6=function(h){var c=h.g9.getVideoContentRect(!0).height,t=h.g9.getVideoContentRect(!0).width;
if(!c||!t)return null;c*=h.XM.height;t*=h.XM.width;return{width:t,height:c}},I4s=function(h,c,t,p){c===255&&t===255||!c&&!t?(++h.U===45&&h.reset(),h.Y.B.clear(),h.T.B.clear()):(h.U=0,M$p(h.Y,c,t,p))},E6=function(h,c){zH.call(this);
this.B=h;this.Y=c;this.track=this.Y.languageName==="CC3"?4:0;this.X=new O5I;this.X.B=1<<this.track},res=function(h,c){if(h.policy.qq&&h.player.d7()){var t=g.pF(c,h.policy,{});
t.set("pot",h.player.d7());t=t.Ob()}else t=g.pF(c,h.policy,{}).Ob();var p={format:"RAW",withCredentials:!0};if(h.policy.y3){p.method="POST";var u=c.Y;u&&Object.keys(u).length>0?p.postBody=g.Bc(u,g.VLe):p.postBody=(0,g.N4)([120,0])}h.T&&(p.responseType="arraybuffer");var q=++h.XM,I=(0,g.lZ)();h.B=g.xU(t,p,3,100,-1,function(b){b.errorCode==="net.timeout"&&h.player.s8("capnt",{rn:q++})}).then(function(b){if(h.policy.Hc&&q%100===1){var C=(0,g.lZ)();
h.player.s8("caprsp",{rn:q,ms:C-I,kb:(b.xhr.responseText.length/1024).toFixed()})}a:{b=b.xhr;h.Ht();if(h.U){var k=!(h.T?b.response:b.responseText)||b.status>=400;if(C=g.KZB(b)){b=g.pF(h.U,h.policy,{});h.U.zQ(b,C);res(h,h.U);break a}if(k)h.player.s8("capfail",{status:b.status});else{var G;g.aS("fcb_r",(0,g.lZ)(),((G=h.player.getVideoData())==null?void 0:G.r9)||"");G=h.U.Ks[0];C=G.O8;h.J!=null&&h.C!==C&&(h.T?h.J(b.response,(G.startTime+h.player.Jf())*1E3):h.J(b.responseText,(G.startTime+h.player.Jf())*
1E3),h.C=C)}}h.U=null;h.B=null}}).qE(function(b){h.U=null;
h.B=null;var C;h.player.s8("capfail",{rn:q,status:(C=b.xhr)==null?void 0:C.status})});
h.U=c;l4e(h.Y,h.U.Ks[0].O8)},Yhr=function(h){var c=void 0,t=g.V_().JU(65);
if(g.oN(h.K)&&t!=null){if(IMT(h)!=null)return!1;c=!t}return c},nL=function(h,c){if(h.storage)try{h.storage.set("module-enabled",c)}catch(t){}},Ncy=function(){return g.j5("yt-player-caption-display-settings")},e2=function(h,c){if(h.B&&(c===void 0||!c)||!h.videoData.captionTracks.length)return!1;
h=h.getAudioTrack();return!!h.X||h.B==="FORCED_ON"},eds=function(h,c){h.player.sP(c);
c=g.H(c);for(var t=c.next();!t.done;t=c.next())g.A3(h.mS,t.value);v$(h.y3)},VB=function(h,c){g.v.call(this);
this.Z=h;this.K=c;this.X=null;this.B=this.Z.nH();this.logger=new g.G7("caps")},CIp=function(h,c){var t=UV6(h);
if(!t)return null;var p=h.B?g.pZ(h.B):null;p&&g.gJR.test(p)&&(c.params.xT=1);var u=h.g9.getPlayerSize();p=u.height*h.XM.height;u=u.width*h.XM.width;h.K.playerStyle!=="google-live"||h.U.isDefault||Object.assign(c.params,h.U);switch(c.params.MJ!=null?c.params.MJ:c.X.length>1?1:0){case 1:return new LL(c,h.U,h.C,t.width,t.height,u,p,h.K.experiments,h.a5.bind(h),h.Z);case 2:return new $N(c,h.U,h.C,t.width,t.height,u,p,h.K.experiments,h.a5.bind(h),h.Z);default:return new O6(c,h.U,h.C,t.width,t.height,u,
p,h.K.experiments,h.a5.bind(h),h.Z)}},JeR=function(h,c){h.K.L("html5_modify_caption_vss_logging")&&(h.videoData.qt=c)},KHs=function(){zH.call(this)},ozy=function(h,c,t,p){var u={};
Object.assign(u,osz(h,c));Object.assign(u,Shs(h,c));p?g.X9(u,h.Y)?(p=h.T,u=h.Y):p="_"+ZX++:p=c.getAttribute("id")||"_"+ZX++;h=kN(c,"t")+t;c=kN(c,"d")||0x8000000000000;if(u.xT===2||u.xT===3)t=u.Zb,u.Zb=u.Y5,u.Y5=t;return new RU(h,c,0,p,u)},O5I=function(){this.U=this.time=this.mode=this.B=0;
this.Y=new rNq(this);this.T=new rNq(this);this.X=[];this.clear()},BGy=function(h){h.row=h.X>0?h.X:1;
h.B=1;A4(h,0,15)},B$=function(h,c,t){this.trackData=h;
this.C=t;this.version=this.T=this.U=this.byteOffset=0;this.B=[];this.X=new DataView(this.trackData)},Mz=function(h){h=g.J$(Math.round(h),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-h.length)+h},zJ1=function(h,c,t,p){p=Object.assign({MJ:0},p);
return new RU(h,c,t,"_"+ZX++,p)},LL=function(h,c,t,p,u,q,I,b,C,k){O6.call(this,h,c,t,p,u,q,I,b,C,k);
this.type=1},mqT=function(h,c){var t,p,u;
return g.l(function(q){if(q.X==1)return t=h+"|"+c,g.T(q,g.DC(),2);if(q.X!=3){p=q.B;if(!p)throw g.tI("gct");return g.T(q,g.bi(p),3)}u=q.B;return q.return(u.get("captions",t))})},iL=function(){this.state=this.Bi=this.X5=0},U6=function(h,c,t,p,u,q,I){q=q===void 0?!1:q;
I=I===void 0?null:I;g.et.call(this,h,h+c,{priority:t,namespace:"captions"});this.windowId=p;this.text=u;this.append=q;this.X=I},w01=function(h,c,t){h.X||(h.X=new KHs);
h=h.X.U(c,t);Math.random()<.01&&g.Kc(Error("Deprecated subtitles format in web player: WebVTT"));return h},H5q=function(h){var c={};
if(h=g.pZ(h))c.lang=h,g.gJR.test(h)&&(c.xT=1);return c},f4T=function(h){if(typeof h==="string")return!1;
h=new B$(h,8,0);return i3p(h)},$N=function(h,c,t,p,u,q,I,b,C,k){O6.call(this,h,c,t,p,u,q,I,b,C,k);
var G=this;this.type=2;this.q2=[];this.r9=this.J=this.ZM=0;this.uB=NaN;this.Xu=0;this.ZT=null;this.Br=new g.SF(this.s_,433,this);this.T&&(k.createClientVe(this.T,this,167342),this.S(this.T,"click",function(){k.logClick(G.T)}),h=new g.Aw(this.element,!0),g.Z(this,h),h.subscribe("hoverstart",function(){k.logVisibility(G.T,!0)},this));
g.iq(this.element,"ytp-caption-window-rollup");g.Z(this,this.Br);g.wI(this.element,"overflow","hidden")},Qer=function(h,c,t,p,u){p===0&&(p=0x8000000000000);
var q={};c.wpWinPosId&&Object.assign(q,h.Y.get(c.wpWinPosId));c.wsWinStyleId&&Object.assign(q,h.T.get(c.wsWinStyleId));h=c.rcRowCount;h!==void 0&&(q.Zb=h);c=c.ccColCount;c!==void 0&&(q.Y5=c);if(q.xT===2||q.xT===3)c=q.Zb,q.Zb=q.Y5,q.Y5=c;return new RU(t,p,0,u,q)},gss=function(h,c,t,p){var u=this;
this.Z=h;this.U=c;this.logger=t;this.Hr=p;this.Uf=[];this.cO=[];this.X=null;this.K2={OA3:function(){return u.X},
Rs:function(){return u.Uf}};
h=g.Ti(this.Z.N().experiments,"html5_override_micro_discontinuities_threshold_ms");this.B=h>0?h:10},$qs=function(h,c,t){var p=h.B,u=!1;
switch(h.style.get()){case 4:case 1:case 2:h.style.get()===4&&p.X>0||(P$(p,t),BGy(h.B),BGy(h.Y),p.row=15,p.X=c,u=!0)}h.style.set(3);h.X=p;h.X.style=h.style;h.U.mode=1<<p.Y;u?p.B=1:p.X!==c&&(p.X>c?(P$(p,t),A4(p,p.row-p.X,c)):p.row<c&&(c=p.X),p.X=c)},Los=function(h){h.style.set(1);
h.X=h.Y;h.X.X=0;h.X.style=h.style;h.U.mode=1<<h.X.Y},FY=function(h,c,t){g.TI.call(this,h);
this.videoData=c;this.audioTrack=t;this.T=c.TX},H$=function(h,c){h=h.getAttribute(c);
if(h!=null)return fL.test(h),h},DVr=function(h,c){switch(h){case 0:return P0I[(c&127)-32];
case 1:return AeI[c&15];case 2:return dVs[c&31];case 3:return a4e[c&31]}return 0},Z56=function(h,c,t){h.hS=h.hS||!!t;
var p={};Object.assign(p,h.X.XY);Object.assign(p,t||c.X);Object.assign(p,h.f2.XY);(t=!h.j)&&qks(h);for(var u=h.mS&&h.y3&&g.X9(p,h.y3)?h.mS:WHs(h,p),q=typeof c.text==="string",I=q?c.text.split("\n"):[c.text],b=0;b<I.length;b++){var C=b>0||!c.append,k=I[b];C&&!t?(qks(h),u=WHs(h,p)):C&&t&&(t=!1);k&&(u.appendChild(q?g.YQ(k):k),q||k.tagName!=="RUBY"||k.childElementCount!==4||g.Uq||!g.Go(k.children[2],"text-emphasis")||(C=h.U?"padding-right":"padding-top",g.Go(k.children[2],"text-emphasis-position")&&(C=
h.U?"padding-left":"padding-bottom"),g.JS?g.wI(u,C,"1em"):g.wI(u,C,"0.5em")))}h.y3=p;h.mS=u;h.C.push(c)},hs=function(h,c){h=h.getAttribute(c);
if(h!=null)return h==="1"},TGm=function(h){var c=1+.25*(h.fontSizeIncrement||0);
if(h.offset===0||h.offset===2)c*=.8;return c},TH=function(h){var c=h.byteOffset;
h.byteOffset+=1;return h.X.getUint8(c)};
g.TI.prototype.t_=g.tc(71,function(){return!1});
g.TI.prototype.KY=g.tc(70,function(){});
g.LA.prototype.KY=g.tc(69,function(h,c,t){var p=this;this.Ht();c=this.JW(h,c);var u=this.jb.N().L("html5_report_captions_ctmp_qoe"),q=(0,g.lZ)();this.yj();Rd1(this,c,{format:"RAW",onSuccess:function(I){p.X=null;if(u){var b=(I.responseText.length/1024).toFixed(),C=(0,g.lZ)();p.videoData.s8("capresp",{ms:C-q,kb:b})}t.tP(I.responseText,h)},
onError:u?function(I){var b;I=(b=I==null?void 0:I.status)!=null?b:0;p.videoData.s8("capfail",{status:I})}:void 0,
withCredentials:!0})});
g.hd.prototype.KY=g.tc(68,function(h,c,t){var p=this;this.Ht();c=this.JW(h,c);this.yj();this.X=g.i$(c,{format:"RAW",onSuccess:function(u){p.X=null;t.tP(u.responseText,h)},
withCredentials:!0})});
g.s2.prototype.H_=g.tc(67,function(){for(var h=g.kq(document,"track",void 0,this.X),c=0;c<h.length;c++)g.t9(h[c])});
g.hw.prototype.H_=g.tc(66,function(){this.mediaElement.H_()});
g.s2.prototype.vZ=g.tc(65,function(){return!(!this.X.textTracks||!this.X.textTracks.addEventListener)});
g.hw.prototype.vZ=g.tc(64,function(){return this.mediaElement.vZ()});
g.s2.prototype.VR=g.tc(63,function(){return!!this.X.textTracks});
g.hw.prototype.VR=g.tc(62,function(){return this.mediaElement.VR()});
g.s2.prototype.zc=g.tc(61,function(h){for(var c=0;c<h.length;c++)this.X.appendChild(h[c])});
g.hw.prototype.zc=g.tc(60,function(h){this.mediaElement.zc(h)});
g.Bx.prototype.kh=g.tc(59,function(h,c,t){this.SC.kh(h,c,t)});
g.D9.prototype.kh=g.tc(58,function(h,c,t){this.B.set(h,{C_:c,YY:t})});
g.R4.prototype.kh=g.tc(57,function(h,c,t){this.XM.kh(h,c,t)});
g.Bx.prototype.zo=g.tc(56,function(h){return this.SC.zo(h)});
g.R4.prototype.zo=g.tc(55,function(h){var c=2;this.T.has(h)?c=0:g.qa(this,h)&&(c=1);return c});
g.yA.prototype.rf=g.tc(43,function(h){var c=this.app.wJ({playerType:void 0});return c?c.rf(h):!1});
g.lq.prototype.rf=g.tc(42,function(h){return this.Pt.BU.rf(h)});
g.h9.prototype.rf=g.tc(41,function(h){return this.VL().some(function(c){return c.namespace===h})});
g.kh.prototype.rf=g.tc(40,function(){return!1});
g.yA.prototype.My=g.tc(38,function(h,c){this.app.E8().My(h,c)});
g.lq.prototype.My=g.tc(37,function(h,c){this.Pt.My(h,c)});
g.Ss.prototype.My=g.tc(36,function(h,c){h=[h,c];g.OD(this,g.r3(this.provider),"cfi",h)});
g.es.prototype.My=g.tc(35,function(h,c){this.qoe&&this.qoe.My(h,c)});
g.mD.prototype.My=g.tc(34,function(h,c){this.tf.My(h,c)});
g.kh.prototype.My=g.tc(33,function(){});
g.yA.prototype.P8=g.tc(32,function(h,c,t){this.app.E8().P8(h,c,t)});
g.lq.prototype.P8=g.tc(31,function(h,c,t){this.Pt.P8(h,c,t)});
g.Ss.prototype.P8=g.tc(30,function(h,c,t){if(this.y3!==h||this.Af!==c)c=c==="rawcc"?"":c,t=[h,c,this.y3,t],g.OD(this,g.r3(this.provider),"cfs",t),this.y3=h,this.Af=c});
g.es.prototype.P8=g.tc(29,function(h,c,t){this.qoe&&this.qoe.P8(h,c,t)});
g.mD.prototype.P8=g.tc(28,function(h,c,t){this.tf.P8(h,c,t)});
g.kh.prototype.P8=g.tc(27,function(){});
g.Ec.prototype.PJ=g.tc(12,function(){return this.J});
g.Lf.prototype.PJ=g.tc(11,function(){return this.E8().nH()});
g.yA.prototype.nH=g.tc(10,function(){return this.app.PJ()});
g.lq.prototype.nH=g.tc(9,function(){return this.Pt.nH()});
g.mD.prototype.nH=g.tc(8,function(){var h;return((h=this.loader)==null?void 0:h.PJ())||null});
g.kh.prototype.nH=g.tc(7,function(){return null});
g.JA.prototype.vn=g.tc(1,function(h){return(h=this.j4(h))?h.X:0});
g.lE.prototype.vn=g.tc(0,function(){return 0});
var AN6=/#(.)(.)(.)/,PI6=/^#(?:[0-9a-f]{3}){1,2}$/i,hJI={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};W$.prototype.contains=function(h){h=g.cp(this.segments,h);return h>=0||h<0&&(-h-1)%2===1};
W$.prototype.length=function(){return this.segments.length/2};
g.L(Kos,g.v);g.J=Kos.prototype;g.J.FM=function(){g.v.prototype.FM.call(this);this.B&&this.B.cancel()};
g.J.TC=function(){this.seekTo(this.player.getCurrentTime())};
g.J.seekTo=function(h){h-=this.player.Jf();var c=this.X;this.X=g.tz(this.r9.i9(h).Ks);c!==this.X&&this.M2&&this.M2()};
g.J.reset=function(){this.Y=new W$;this.C=-1;this.B&&(this.B.cancel(),this.B=null)};
g.J.f1=function(){this.Ht();var h;if(h=this.X!=null)h=this.X,h=h.X.KA(h);if(h&&!this.B&&!(this.X&&this.X.startTime-this.player.getCurrentTime()>30)){h=this.X;h=h.X.Qb(h);var c=h.Ks[0],t;if((t=this.player.getVideoData())==null?0:t.enableServerStitchedDai)if(t=this.player.nH()){var p=c.X.info.id,u=c.O8,q=h.Ks[0].T;if(this.policy.y3){if(t=t.xS(q,u,p,3))h.Y=t}else if(p=t.QY(q,u,p,3))if(t=t.zo(u),t===0)p&&(h.X=new g.vM(p));else if(t===2){this.j.start();gzy(this)&&this.seekTo(this.player.getCurrentTime());
return}}c.X.index.e4(c.O8)?(this.Y.contains(h.Ks[0].O8)||res(this,h),this.X=g.tz(h.Ks)):gzy(this)&&this.seekTo(this.player.getCurrentTime())}this.j.start()};
g.L(rV,g.TI);g.J=rV.prototype;g.J.KY=function(h,c,t){var p=this;this.yj();c=zds(this,h.getId());c||(c=h.languageCode,c=this.X.isManifestless?ubz(this,c,"386"):ubz(this,c));if(c){var u=(c.index.vn(c.index.Ek())-c.index.getStartTime(c.index.Ek()))*1E3,q=new g.SSU(this.Z.N());this.Y=new Kos(q,this.Z,c,function(I,b){t.tP(I,h,b,u)},this.j||g.y3(c.info),function(){p.Y&&p.Y.reset();
p.C=!0})}};
g.J.t_=function(){var h=this.C;this.C=!1;return h};
g.J.wc=function(h){var c=this.Z.N().L("html5_fallback_if_rawcc_missing");var t=this.X.X.rawcc!=null;if(!this.j||!t&&c)c=this.X.isManifestless?ce1(this,"386"):ce1(this);else{if(!t){g.B5(this.logger,386248249,"rawcc used but unavailable");return}c=[new g.Fx({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Fx({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}c=g.H(c);
for(t=c.next();!t.done;t=c.next())g.rz(this.B,t.value);h.KN()};
g.J.yj=function(){this.Y&&(this.Y.dispose(),this.Y=null)};
g.J.JW=function(){return""};
var fL=/^#(?:[0-9a-f]{3}){1,2}$/i;var aMs=["left","right","center","justify"];g.L(O6,g.Q);g.J=O6.prototype;g.J.qS=function(h,c){this.bB=h;this.eb=c;var t=g.$2(this.element,this.element.parentElement);this.N2=h-t.x;this.g9=c-t.y};
g.J.Uo=function(h,c){if(h!==this.bB||c!==this.eb){g.gR(this.element,"ytp-dragging")||g.iq(this.element,"ytp-dragging");var t=g.uO(this.element);h=h-this.N2-.02*this.Fs;var p=c-this.g9-.02*this.dF,u=(h+t.width/2)/this.maxWidth*3;u=Math.floor(g.J$(u,0,2));var q=(p+t.height/2)/this.maxHeight*3;q=Math.floor(g.J$(q,0,2));c=u+q*3;h=(h+u/2*t.width)/this.maxWidth;h=g.J$(h,0,1)*100;t=(p+q/2*t.height)/this.maxHeight;t=g.J$(t,0,1)*100;this.B.params.oM=c;this.B.params.Tm=t;this.B.params.AZ=h;this.B.params.isDefault=
!1;this.X.oM=c;this.X.Tm=t;this.X.AZ=h;this.X.isDefault=!1;this.XM.oM=c;this.XM.Tm=t;this.XM.AZ=h;this.XM.isDefault=!1;this.X6()}};
g.J.F7=function(){g.NP(this.element,"ytp-dragging")};
g.J.X6=function(){this.K$(this.C)};
g.J.K$=function(h){var c=this.Pr?0:Math.min(this.rG(),this.maxWidth),t=this.ML(),p=this.Pr;if(p){var u=getComputedStyle(this.Y.parentNode);u=xN(u.borderLeftWidth)+xN(u.borderRightWidth)+xN(u.paddingLeft)+xN(u.paddingRight)}else u=0;var q=u;u="";this.B.params.xT===3&&(u="rotate(180deg)");var I=p?"calc(96% - "+q+"px)":"96%";g.wI(this.element,{top:0,left:0,right:"",bottom:"",width:c?c+"px":"",height:t?t+"px":"","max-width":I,"max-height":I,margin:"",transform:""});this.nL(h);u={transform:u,top:"",left:"",
width:c?c+"px":"",height:t?t+"px":"","max-width":"","max-height":""};var b=this.X.AZ*.96+2;I=this.X.oM;switch(I){case 0:case 3:case 6:(p=this.X.XY.fontSizeIncrement)&&p>0&&this.X.xT!==2&&this.X.xT!==3&&(b=Math.max(b/(1+p*2),2));u.left=b+"%";break;case 1:case 4:case 7:u.left=b+"%";b=this.Y.offsetWidth;c||b?(c=c||b+1,u.width=c+"px",u["margin-left"]=p?c/-2-q/2+"px":c/-2+"px"):u.transform+=" translateX(-50%)";break;case 2:case 5:case 8:u.right=100-b+"%"}p=this.X.Tm*.96+2;switch(I){case 0:case 1:case 2:u.top=
p+"%";break;case 3:case 4:case 5:u.top=p+"%";(t=t||this.element.clientHeight)?(u.height=t+"px",u["margin-top"]=t/-2+"px"):u.transform+=" translateY(-50%)";break;case 6:case 7:case 8:u.bottom=100-p+"%"}g.wI(this.element,u);if(this.T){t=this.Y.offsetHeight;p=1;for(c=0;c<h.length;c++)u=h[c],typeof u.text==="string"&&(p+=u.text.split("\n").length-1,u.append||c===0||p++);t/=p;this.T.style.height=t+"px";this.T.style.width=t+"px";this.element.style.paddingLeft=t+5+"px";this.element.style.paddingRight=t+
5+"px";h=Number(this.element.style.marginLeft.replace("px",""))-t-5;t=Number(this.element.style.marginRight.replace("px",""))-t-5;this.element.style.marginLeft=h+"px";this.element.style.marginRight=t+"px"}};
g.J.nL=function(h){var c;for(c=0;c<h.length&&h[c]===this.C[c];c++);if(this.hS||this.C.length>c)c=0,this.hS=!1,this.C=[],this.j=this.y3=this.mS=null,g.So(this.Y);for(;c<h.length;c++)Z56(this,h[c])};
g.J.rG=function(){return 0};
g.J.ML=function(){return 0};
g.J.toString=function(){return g.Q.prototype.toString.call(this)};O5I.prototype.clear=function(){this.U=this.time=this.mode=0;this.X=[];this.reset()};
O5I.prototype.reset=function(){this.mode=0;this.Y.reset(0);this.T.reset(1)};
var jeq=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];XY.prototype.set=function(h){this.type=h};
XY.prototype.get=function(){return this.type};
iL.prototype.clear=function(){this.state=0};
iL.prototype.update=function(){this.state=this.state===2?1:0};
iL.prototype.Cr=function(){return this.state!==0};
iL.prototype.matches=function(h,c){return this.Cr()&&h===this.X5&&c===this.Bi};
Foq.prototype.reset=function(){this.timestamp=this.X=0};
aU.prototype.updateTime=function(h){for(var c=1;c<=15;++c)for(var t=1;t<=32;++t)this.U[c][t].timestamp=h};
aU.prototype.debugString=function(){for(var h="\n",c=1;c<=15;++c){for(var t=1;t<=32;++t){var p=this.U[c][t];h=p.X===0?h+"_":h+String.fromCharCode(p.X)}h+="\n"}return h};
aU.prototype.reset=function(h){for(var c=0;c<=15;c++)for(var t=0;t<=32;t++)this.U[c][t].reset();this.Y=h;this.X=0;this.B=this.row=1};
var P0I=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],AeI=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],dVs=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],a4e=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];O3y.prototype.reset=function(h,c){this.T=c;this.style.set(2);this.B=this.C;this.Y=this.j;this.X=this.B;var t=(h<<2)+(c<<1);this.C.reset(t);this.j.reset(t);this.text.reset((h<<2)+(c<<1)+1)};
rNq.prototype.reset=function(h){this.T=h;this.B.clear();this.Y=this.U;this.U.reset(h,0);this.C.reset(h,1)};mVs.prototype.Y=function(){};g.L(U6,g.et);U6.prototype.toString=function(){return g.et.prototype.toString.call(this)};g.L(zH,g.v);zH.prototype.reset=function(){};g.L(RU,g.et);RU.prototype.toString=function(){return g.et.prototype.toString.call(this)};
var ZX=0;g.L(S2,zH);S2.prototype.reset=function(){this.j={};this.B=this.X=null;this.C=!0};
S2.prototype.U=function(h,c){h=h.firstChild;h.getAttribute("format");c=c||0;Number.isFinite(c);h=Array.from(h.childNodes);h=g.H(h);for(var t=h.next();!t.done;t=h.next())if(t=t.value,t.nodeType===1)switch(t.tagName){case "head":var p=t;break;case "body":var u=t}if(p)for(p=Array.from(p.childNodes),p=g.H(p),h=p.next();!h.done;h=p.next())if(h=h.value,h.nodeType===1)switch(h.tagName){case "pen":t=h.getAttribute("id");var q=this.pens,I={},b=h.getAttribute("p");b&&Object.assign(I,this.pens[b]);b=hs(h,"b");
b!=null&&(I.bold=b);b=hs(h,"i");b!=null&&(I.italic=b);b=hs(h,"u");b!=null&&(I.underline=b);b=GH(h,"et");b!=null&&(I.charEdgeStyle=b);b=GH(h,"of");b!=null&&(I.offset=b);b=H$(h,"bc");b!=null&&(I.background=b);b=H$(h,"ec");b!=null&&(I.M3=b);b=H$(h,"fc");b!=null&&(I.color=b);b=GH(h,"fs");b!=null&&b!==0&&(I.fontFamily=b);b=kN(h,"sz");b!==void 0&&(I.fontSizeIncrement=b/100-1);b=kN(h,"bo");b!==void 0&&(I.backgroundOpacity=b/255);b=kN(h,"fo");b!==void 0&&(I.textOpacity=b/255);b=GH(h,"rb");b!=null&&b!==10&&
b!==0&&(I.h$=b>10?b-1:b);h=GH(h,"hg");h!=null&&(I.gG=h);q[t]=I;break;case "ws":t=h.getAttribute("id");this.M2[t]=Shs(this,h);break;case "wp":t=h.getAttribute("id"),this.J[t]=osz(this,h)}if(u){p=[];u=Array.from(u.childNodes);u=g.H(u);for(h=u.next();!h.done;h=u.next())if(h=h.value,h.nodeType===1)switch(h.tagName){case "w":this.X=ozy(this,h,c,!1);(h=this.j[this.X.id])&&h.end>this.X.start&&(h.end=this.X.start);this.j[this.X.id]=this.X;p.push(this.X);break;case "p":var C=h;b=c;t=[];q=C.getAttribute("w")||
this.T;I=!!hs(C,"a");b=(kN(C,"t")||0)+b;var k=kN(C,"d")||5E3;I||(!this.C&&this.B&&this.B.windowId===q&&this.B.end>b&&(this.B.end=b),this.B&&this.B.text==="\n"&&(this.B.text=""));var G=I?6:5,D=C.getAttribute("p");D=D?this.pens[D]:null;var m=Array.from(C.childNodes);m.length&&(this.C=C.getAttribute("d")!=null);for(C=0;C<m.length;C++){var f=m[C],R=void 0;C>0&&(I=!0);var X=void 0;f.nodeType===1&&(X=f);if(X&&X.tagName==="s"){if((f=(f=X.getAttribute("p"))?this.pens[f]:null)&&f.h$&&(f.h$===1?(f=m.slice(C,
C+4),f.length===4&&(R=Q2z(b,k,q,I,G,f,this.pens),C+=3)):R=Q2z(b,k,q,I,G,[X],this.pens)),!R){var O=X;R=b;X=k;f=q;var w=I,z=G,P=O.textContent?O.textContent:"",a=O.getAttribute("p");a=a?this.pens[a]:null;O=kN(O,"t")||0;R=new U6(R+O,X-O,z,f,P,w,a)}}else R=new U6(b,k,G,q,f.textContent||"",I,D);t.push(R);this.B=R}if(t.length>0)for(t[0].windowId===this.T&&(this.X=ozy(this,h,c,!0),p.push(this.X)),h=g.H(t),t=h.next();!t.done;t=h.next())t=t.value,t.windowId=this.X.id,this.X.X.push(t),p.push(t)}c=p}else c=[];
return c};var vzq=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.L(wV,zH);wV.prototype.reset=function(){this.B.clear()};
wV.prototype.U=function(h,c){var t=JSON.parse(h);if(!t)return[];if(t.pens){h=0;for(var p=g.H(t.pens),u=p.next();!u.done;u=p.next()){u=u.value;var q={},I=u.pParentId;I&&Object.assign(q,this.X.get(I));u.bAttr&&(q.bold=!0);u.iAttr&&(q.italic=!0);u.uAttr&&(q.underline=!0);I=u.ofOffset;I!=null&&(q.offset=I);u.szPenSize!==void 0&&(q.fontSizeIncrement=u.szPenSize/100-1);I=u.etEdgeType;I!=null&&(q.charEdgeStyle=I);u.ecEdgeColor!==void 0&&(q.M3=Mz(u.ecEdgeColor));I=u.fsFontStyle;I!=null&&I!==0&&(q.fontFamily=
I);u.fcForeColor!==void 0&&(q.color=Mz(u.fcForeColor));u.foForeAlpha!==void 0&&(q.textOpacity=u.foForeAlpha/255);u.bcBackColor!==void 0&&(q.background=Mz(u.bcBackColor));u.boBackAlpha!==void 0&&(q.backgroundOpacity=u.boBackAlpha/255);(I=u.rbRuby)&&I!==10&&(q.h$=I>10?I-1:I,q.textEmphasis=vzq.get(q.h$));u.hgHorizGroup&&(q.gG=u.hgHorizGroup);this.X.set(h++,q)}}if(t.wsWinStyles)for(h=0,p=g.H(t.wsWinStyles),u=p.next();!u.done;u=p.next())u=u.value,q={},(I=u.wsParentId)?Object.assign(q,this.T.get(I)):Object.assign(q,
this.C),u.mhModeHint!==void 0&&(q.MJ=u.mhModeHint),u.juJustifCode!==void 0&&(q.textAlign=u.juJustifCode),u.pdPrintDir!==void 0&&(q.xT=u.pdPrintDir),u.sdScrollDir!==void 0&&(q.rE=u.sdScrollDir),u.wfcWinFillColor!==void 0&&(q.windowColor=Mz(u.wfcWinFillColor)),u.wfoWinFillAlpha!==void 0&&(q.windowOpacity=u.wfoWinFillAlpha/255),this.T.set(h++,q);if(t.wpWinPositions)for(h=0,p=g.H(t.wpWinPositions),u=p.next();!u.done;u=p.next())u=u.value,q={},(I=u.wpParentId)&&Object.assign(q,this.Y.get(I)),u.ahHorPos!==
void 0&&(q.AZ=u.ahHorPos),u.apPoint!==void 0&&(q.oM=u.apPoint),u.avVerPos!==void 0&&(q.Tm=u.avVerPos),u.ccCols!==void 0&&(q.Y5=u.ccCols),u.rcRows!==void 0&&(q.Zb=u.rcRows),this.Y.set(h++,q);if(t.events){h=[];t=g.H(t.events);for(p=t.next();!p.done;p=t.next()){var b=p.value;u=(b.tStartMs||0)+c;q=b.dDurationMs||0;if(b.id)I=String(b.id),p=Qer(this,b,u,q,I),h.push(p),this.B.set(I,p);else{b.wWinId?I=b.wWinId.toString():(I="_"+ZX++,p=Qer(this,b,u,q,I),h.push(p),this.B.set(I,p));p=h;var C=b;q===0&&(q=5E3);
b=this.B.get(I);var k=!!C.aAppend,G=k?6:5,D=C.segs,m=null;C.pPenId&&(m=this.X.get(C.pPenId));for(C=0;C<D.length;C++){var f=D[C],R=f.utf8;if(R){var X=f.tOffsetMs||0,O=null;f.pPenId&&(O=this.X.get(f.pPenId));if((b.params.MJ!=null?b.params.MJ:b.X.length>1?1:0)===2&&k&&R==="\n")continue;f=null;var w=[],z;if(z=O&&O.h$===1){z=D;var P=C;if(P+3>=z.length||!z[P+1].pPenId||!z[P+2].pPenId||!z[P+3].pPenId)z=!1;else{var a=z[P+1].pPenId;(a=this.X.get(a))&&a.h$&&a.h$===2?(a=z[P+2].pPenId,a=this.X.get(a),!a||!a.h$||
a.h$<3?z=!1:(a=z[P+3].pPenId,z=(a=this.X.get(a))&&a.h$&&a.h$===2?!0:!1)):z=!1}}if(z)X=D[C+1].utf8,f=D[C+3].utf8,z=D[C+2].utf8,P=this.X.get(D[C+2].pPenId),R=H36(R,X,z,f,P),f=new U6(u,q,G,I,R,k,O),C+=3;else{if(R.indexOf("<")>-1){var x=void 0;w=O;z=m;P=u;a=q;var B=X,e=G,gm=k,U=[],pQ=g.k_("<html>"+R+"</html>");if(!pQ.getElementsByTagName("parsererror").length&&((x=pQ.firstChild)==null?0:x.childNodes.length))for(x=g.H(pQ.firstChild.childNodes),pQ=x.next();!pQ.done;pQ=x.next()){pQ=pQ.value;var YZ=void 0,
c9=void 0,lO=(c9=(YZ=pQ.textContent)==null?void 0:YZ.replace(/\n/g,""))!=null?c9:"";if(pQ.nodeType!==3||lO&&lO.match(/^ *$/)==null){YZ={};Object.assign(YZ,w||z);c9=void 0;switch((c9=pQ)==null?void 0:c9.tagName){case "b":YZ.bold=!0;break;case "i":YZ.italic=!0;break;case "u":YZ.underline=!0}U.push(new U6(P+B,a-B,e,b.id,lO,gm,YZ))}}w=U}w.length||(w=[new U6(u+X,q-X,G,b.id,R,k,O||m)])}if(w.length)for(k=g.H(w),O=k.next();!O.done;O=k.next())O=O.value,p.push(O),b.X.push(O);else f&&(p.push(f),b.X.push(f))}k=
!0}}}c=h}else c=[];return c};g.L(FY,g.TI);FY.prototype.KY=function(h,c,t){fMR(this.videoData.videoId,h.vssId,t.tP)};
FY.prototype.wc=function(h){if(this.audioTrack)for(var c=g.H(this.audioTrack.captionTracks),t=c.next();!t.done;t=c.next())g.rz(this.B,t.value);h.KN()};g.L(LL,O6);LL.prototype.nL=function(h){var c=this.B.X;O6.prototype.nL.call(this,h);for(h=h.length;h<c.length;h++){var t=c[h];if(q&&t.X===u)var p=q;else{p={};Object.assign(p,t.X);Object.assign(p,xVz);var u=t.X;var q=p}Z56(this,t,p)}};
var xVz={E5:!0};g.L(B$,mVs);B$.prototype.Y=function(h,c,t,p,u){if(t<p){var q="_"+ZX++;t=t/1E3-this.C;p=p/1E3-this.C;h=new RU(t,p-t,5,q,{textAlign:0,oM:0,AZ:c*2.5,Tm:h*5.33});u=new U6(t,p-t,5,q,u);this.B.push(h);this.B.push(u)}};
g.L(E6,zH);E6.prototype.U=function(h){h=new B$(h,h.byteLength,this.B);if(i3p(h)){for(;h.byteOffset<h.X.byteLength;)for(h.version===0?h.U=J4(h)*(1E3/45):h.version===1&&(h.U=J4(h)*4294967296+J4(h)),h.T=TH(h);h.T>0;h.T--){var c=TH(h),t=TH(h),p=TH(h);c&4&&(c&3)===this.track&&(this.track===0||this.track===1)&&(c=this.X,c.X.push({time:h.U,type:this.track,EF:t,nt:p,order:c.X.length}))}Yks(this.X,h);return h.B}return[]};
E6.prototype.reset=function(){this.X.clear()};g.L($N,O6);g.J=$N.prototype;g.J.X6=function(){g.M8(this.Br)};
g.J.s_=function(){this.element.removeEventListener("transitionend",this.s_,!1);g.NP(this.element,"ytp-rollup-mode");this.K$(this.ZT,!0)};
g.J.ML=function(){return this.U?this.r9:this.J};
g.J.rG=function(){return this.U?this.J:this.r9};
g.J.K$=function(h,c){this.ZT=h;if(this.B.params.Zb){for(var t=0,p=0;p<this.C.length&&t<h.length;p++)this.C[p]===h[t]&&t++;t>0&&t<h.length&&(h=this.C.concat(h.slice(t)));this.Xu=this.r9;this.J=this.r9=0;O6.prototype.K$.call(this,h);Gup(this,c)}O6.prototype.K$.call(this,h)};gss.prototype.unload=function(){this.X!=null&&(this.Z.removeEventListener("sabrCaptionsDataLoaded",this.X),this.X=null);this.Uf=[];this.Z.publish("sabrCaptionsBufferedRangesUpdated",this.Uf)};
gss.prototype.NN=function(h){return{formatId:g.te(h.info.X.info,this.Hr),O8:h.info.O8+(this.Hr?0:1),startTimeMs:h.info.T*1E3,durationMs:h.info.J*1E3}};g.L(DX,g.TI);DX.prototype.KY=function(h,c,t){this.yj();c=h.getId();c=c!=null&&c in this.X.X?this.X.X[c]:null;c||(c=h.languageCode,c=this.X.isManifestless?xqz(this,c,"386"):xqz(this,c));c&&(this.Y=h,this.C=c,i5m(this.j,t),this.Z.publish("sabrCaptionsTrackChanged",g.te(c.info,this.X.Hr)))};
DX.prototype.wc=function(h){var c=this.X.isManifestless?wCz(this,"386"):wCz(this);c=g.H(c);for(var t=c.next();!t.done;t=c.next())g.rz(this.B,t.value);h.KN()};
DX.prototype.yj=function(){this.Y&&(this.Y=this.C=null,this.j.unload(),this.Z.publish("sabrCaptionsTrackChanged",null))};
DX.prototype.JW=function(){return""};var seR="WEBVTT".split("").map(function(h){return h.charCodeAt(0)});
g.L(KHs,zH);
KHs.prototype.U=function(h,c){h instanceof ArrayBuffer&&(h=g.sL(new Uint8Array(h)));var t=[];h=h.split(SkI);for(var p=1;p<h.length;p++){var u=h[p],q=c;if(u!==""&&!nz1.test(u)){var I=eJm.exec(u);if(I&&I.length>=4){var b=Gme(I[1]),C=Gme(I[2])-b;b+=q;var k=(I=I[3])?I.split(" "):[];I={};var G=null;var D="";var m=null,f="";k=g.H(k);for(var R=k.next();!R.done;R=k.next())if(R=R.value.split(":"),R.length===2){var X=R[1];switch(R[0]){case "line":R=X.split(",");R[0].endsWith("%")&&(G=R[0],I.Tm=Number.parseInt(G,
10),R.length===2&&(D=R[1].trim()));break;case "position":R=X.split(",");m=R[0];I.AZ=Number.parseInt(m,10);R.length===2&&(f=R[1].trim());break;case "align":switch(X){case "start":I.textAlign=0;break;case "middle":I.textAlign=2;break;case "end":I.textAlign=1}}}G||D||(D="end");if(!m)switch(I.textAlign){case 0:I.AZ=0;break;case 1:I.AZ=100;break;case 2:I.AZ=50}if(I.textAlign!=null){G=0;switch(D){case "center":G+=3;break;case "end":G+=6;break;default:G+=0}switch(f){case "line-left":G+=0;break;case "center":G+=
1;break;case "line-right":G+=2;break;default:switch(I.textAlign){case 0:G+=0;break;case 2:G+=1;break;case 1:G+=2}}D=G<0||G>8?7:G;I.oM=D}u=u.substring(eJm.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");f=I;I=u;u={};if(I.indexOf("<")<0&&I.indexOf("&")<0)q=zJ1(b,C,5,f),C=new U6(b,C,5,q.id,I,!1,g.mr(u)?void 0:u),t.push(q),t.push(C),q.X.push(C);else for(D=I.split(yez),D.length===1?(I=5,f=zJ1(b,C,I,f)):(G=I=6,f=Object.assign({Y5:32},f),f=new RU(b,C,G,"_"+ZX++,f)),t.push(f),G=b,m=0;m<D.length;m++)k=D[m],
m%2===0?(R=g.k_("<html>"+k+"</html>"),R.getElementsByTagName("parsererror").length?(X=R.createElement("span"),X.appendChild(R.createTextNode(k))):X=R.firstChild,tFq(this,G,C-(G-b),I,f,m>0,X,u,t)):G=Gme(k)+q}eJm.lastIndex=0}}return t};
var nz1=/^NOTE/,SkI=/(?:\r\n|\r|\n){2,}/,eJm=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),yez=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.L(VB,g.v);VB.prototype.clear=function(){this.X&&this.X.dispose();this.X=null};
VB.prototype.reset=function(){this.X&&this.X.reset()};
VB.prototype.FM=function(){g.v.prototype.FM.call(this);this.clear()};var md={windowColor:"#080808",windowOpacity:0,textAlign:2,oM:7,AZ:50,Tm:100,isDefault:!0,XY:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.L(Tcz,g.dy);g.J=Tcz.prototype;g.J.FM=function(){if(this.T||this.uB){var h=this.Z.Vl();h&&!h.Ht()&&h.H_()}else yNs(this,!1);g.dy.prototype.FM.call(this)};
g.J.iO=function(){return this.K.L("html5_honor_caption_availabilities_in_audio_track")&&this.Y!=="LIVE"&&this.Y!=="SABR_LIVE"};
g.J.RM=function(){if(this.bB)return this.T||this.uB;var h=this.getAudioTrack();if(this.iO()){if(!h.captionTracks.length)return!1;if(!this.X)return!0}h=qhs(h,g.oN(this.K));return h==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:h==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?e2(this):Yhr(this)||e2(this)?!0:b3y(this)};
g.J.load=function(){g.dy.prototype.load.call(this);this.M2=this.getAudioTrack();if(this.X)this.B&&(this.eb.clear(),this.T?lMs(this,!0):this.player.getPresentingPlayerType()!==3&&this.X.KY(this.B,"json3",this.Br),this.T||this.uB||oU(this)||this.player.F3("captionschanged",g.Bo(this.B)));else{var h;this.Y==="OFFLINE"?h=new FY(this.player,this.videoData,this.getAudioTrack()):this.Y==="SABR_LIVE"?h=new DX(this.videoData.X,this.player):this.Y==="LIVE"?h=new rV(this.videoData.X,this.player):this.Y==="INNERTUBE"?
h=new g.LA(this.player,this.videoData,this.getAudioTrack()):h=new g.hd(this.player,this.videoData.TW,this.videoData.videoId,g.Xnt(this.videoData),this.videoData.Fg,this.videoData.eventId);this.X=h;g.Z(this,this.X);this.X.wc(this.Br)}};
g.J.unload=function(){this.T&&this.B?lMs(this,!1):(this.ZM&&g.UN(this.ZM),this.player.DP("captions"),this.mS=[],this.X&&this.X.yj(),this.eb.clear(),this.r9&&this.player.bX(this.r9),this.yr());g.dy.prototype.unload.call(this);this.player.d8();this.player.F3("captionschanged",{})};
g.J.create=function(){this.RM()&&this.load();var h;a:{var c,t,p;if(this.K.L("web_player_nitrate_promo_tooltip")&&((c=this.videoData.getPlayerResponse())==null?0:(t=c.captions)==null?0:(p=t.playerCaptionsTracklistRenderer)==null?0:p.enableTouchCaptionsNitrate)){var u,q;if(c=(h=this.videoData.getPlayerResponse())==null?void 0:(u=h.captions)==null?void 0:(q=u.playerCaptionsTracklistRenderer)==null?void 0:q.captionTracks)for(h=g.H(c),u=h.next();!u.done;u=h.next())if(u=u.value,u.kind==="asr"&&u.languageCode===
"en"){h=!0;break a}}h=!1}h&&this.Z.publish("showpromotooltip",this.j.element)};
g.J.KN=function(){var h=qhs(this.player.getAudioTrack(),g.oN(this.K));var c=h==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?Nz(this,this.J):h==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&e2(this)?lL(this):Yhr(this)||this.J||b3y(this)?Nz(this,this.J):e2(this)?lL(this):null;if(this.T||this.uB){var t=g.KK(this.X.B,!0);h=[];for(var p=0;p<t.length;p++){var u=t[p],q=g.Cl("TRACK");q.setAttribute("kind","subtitles");q.setAttribute("label",g.ai(u));q.setAttribute("srclang",g.pZ(u));q.setAttribute("id",u.toString());
this.uB||q.setAttribute("src",this.X.JW(u,"vtt"));u===c&&q.setAttribute("default","1");h.push(q)}c=this.Z.Vl();c.zc(h);h=c.Ig();this.Pr&&this.hS.S(h.textTracks,"change",this.gcs)}else!this.B&&c&&yB(this,c),this.player.F3("onCaptionsTrackListChanged"),this.player.Ld("onApiChange")};
g.J.gcs=function(){for(var h=this.Z.Vl().Ig().textTracks,c=null,t=0;t<h.length;t++)if(h[t].mode==="showing")a:{c=g.KK(this.X.B,!0);for(var p=0;p<c.length;p++)if(c[p].toString()===h[t].id){c=c[p];break a}c=null}(this.loaded?this.B:null)!==c&&yB(this,c,!0)};
g.J.jt2=function(){!this.B&&this.T||this.unload()};
g.J.tP=function(h,c,t,p){if(h){var u;JeR(this,(u=this.B)!=null?u:void 0);this.X.t_()&&(this.mS=[],this.Z.DP("captions"),v$(this.y3),this.eb.reset());a:{u=this.eb;p=p||0;t=RJ6(u,h,t||0);h=[];try{for(var q=g.H(t),I=q.next();!I.done;I=q.next()){var b=I.value,C=b.trackData,k=b.sB,G=u.K.L("safari_live_drm_captions_fix");if(typeof C!=="string"){t=h;var D=t.concat;if(G&&p01(C))var m=w01(u,C,k);else{var f=u,R=c,X=C,O=k,w=p;if(!f4T(X))throw Error("Invalid binary caption track data");f.X||(f.X=new E6(w,R));
m=f.X.U(X,O)}var z=D.call(t,m)}else{if(C.substring(0,6)==="WEBVTT")var P=h.concat(w01(u,C,k));else{t=h;var a=t.concat;b:{R=f=void 0;X=u;O=c;if(C[0]==="{")try{X.X||(X.X=new wV(H5q(O)));var x=R=X.X.U(C,k);break b}catch(c9){g.iI(c9);x=[];break b}var B=g.k_(C);if(!B||!B.firstChild){var e=Error("Invalid caption track data");e.params=C;throw e;}if(B.firstChild.tagName==="timedtext"){if(Number(B.firstChild.getAttribute("format"))===3){X.X||(X.X=new S2(H5q(O),X.K));x=f=X.X.U(B,k);break b}var gm=Error("Unsupported subtitles format in web player (Format2)");
gm.params=C;throw gm;}if(B.firstChild.tagName==="transcript"){var U=Error("Unsupported subtitles format in web player (Format1)");U.params=C;throw U;}var pQ=Error("Invalid caption track data");pQ.params=C;throw pQ;}P=a.call(t,x)}z=P}h=z}var YZ=h;break a}catch(c9){g.B5(u.logger,187101178,"Captions parsing failed: "+c9.message+". ");u.clear();YZ=[];break a}YZ=void 0}c=YZ;c.length>0&&(YZ=this.B,this.P8(YZ,!!YZ,oU(this)?"g":this.J?"m":"s"));this.player.bX(c,void 0,this.Y==="LIVE"||this.Y==="SABR_LIVE");
!this.J||this.uB||oU(this)||g.ct(this.K)||g.sI(this.K)||g.yr(this.K)||this.K.hS==="shortspage"||this.player.isInline()||(g.UN(this.ZM),c=ns1({oM:0,AZ:5,Tm:5,Zb:2,textAlign:0,xT:0,lang:"fr"}),this.GM=[c],YZ=["Cliquez sur "," pour acc\u00e9der aux param\u00e8tres."],this.N2||(q=new g.JI(g.Y1()),g.Z(this,q),this.N2=q.element),q=c.end-c.start,(I=g.ai(this.B))&&this.GM.push(new U6(c.start,q,0,c.id,I)),this.GM.push(new U6(c.start,q,0,c.id,YZ[0]),new U6(c.start,q,0,c.id,this.N2,!0),new U6(c.start,q,0,c.id,
YZ[1],!0)),this.player.bX(this.GM),g.ve(this.ZM));!this.J||this.uB||oU(this)||(g.oN(this.K)?KL(this,!0):nL(this,!0),this.M2&&(this.M2.Y=this.B),this.player.d8());this.J=!1}};
g.J.onCueRangeEnter=function(h){this.mS.push(h);v$(this.y3)};
g.J.onCueRangeExit=function(h){g.A3(this.mS,h);this.X instanceof rV&&this.X.j&&this.player.sP([h]);v$(this.y3)};
g.J.getCaptionWindowContainerId=function(){return this.j.element.id};
g.J.Qik=function(){eds(this,this.GM);this.GM=null};
g.J.JV=function(){var h=this;if(!this.Xu||!this.T){this.y3.stop();g.cMC(this.AS);this.mS.sort(g.lUm);var c=this.mS;if(this.r9){var t=g.Rv(c,function(q){return this.r9.indexOf(q)===-1},this);
t.length&&(c=t)}c=g.H(c);for(t=c.next();!t.done;t=c.next())kme(this,t.value);c=g.H(Object.entries(this.q2));var p=c.next();for(t={};!p.done;t={Hl:void 0,zm:void 0},p=c.next()){var u=g.H(p.value);p=u.next().value;u=u.next().value;t.Hl=p;t.zm=u;this.AS[t.Hl]?(t.zm.element.parentNode||(t.zm instanceof $N||t.zm instanceof LL||g.wQ(this.q2,function(q){return function(I,b){b!==q.Hl&&I.B.params.oM===q.zm.B.params.oM&&I.B.params.AZ===q.zm.B.params.AZ&&I.B.params.Tm===q.zm.B.params.Tm&&(I.dispose(),delete h.q2[b]);
return b===q.Hl}}(t),this),this.j.element.appendChild(t.zm.element)),t.zm.K$(this.AS[t.Hl])):(t.zm.dispose(),delete this.q2[t.Hl])}}};
g.J.Bq9=function(){j2p(this,{},!0);this.player.F3("captionssettingschanged")};
g.J.fJ=function(){var h=md.XY;h={background:h.background,backgroundOpacity:h.backgroundOpacity,charEdgeStyle:h.charEdgeStyle,color:h.color,fontFamily:h.fontFamily,fontSizeIncrement:h.fontSizeIncrement,fontStyle:h.bold&&h.italic?3:h.bold?1:h.italic?2:0,textOpacity:h.textOpacity,windowColor:md.windowColor,windowOpacity:md.windowOpacity};var c=Ncy()||{};c.background!=null&&(h.background=c.background);c.backgroundOverride!=null&&(h.backgroundOverride=c.backgroundOverride);c.backgroundOpacity!=null&&(h.backgroundOpacity=
c.backgroundOpacity);c.backgroundOpacityOverride!=null&&(h.backgroundOpacityOverride=c.backgroundOpacityOverride);c.charEdgeStyle!=null&&(h.charEdgeStyle=c.charEdgeStyle);c.charEdgeStyleOverride!=null&&(h.charEdgeStyleOverride=c.charEdgeStyleOverride);c.color!=null&&(h.color=c.color);c.colorOverride!=null&&(h.colorOverride=c.colorOverride);c.fontFamily!=null&&(h.fontFamily=c.fontFamily);c.fontFamilyOverride!=null&&(h.fontFamilyOverride=c.fontFamilyOverride);c.fontSizeIncrement!=null&&(h.fontSizeIncrement=
c.fontSizeIncrement);c.fontSizeIncrementOverride!=null&&(h.fontSizeIncrementOverride=c.fontSizeIncrementOverride);c.fontStyle!=null&&(h.fontStyle=c.fontStyle);c.fontStyleOverride!=null&&(h.fontStyleOverride=c.fontStyleOverride);c.textOpacity!=null&&(h.textOpacity=c.textOpacity);c.textOpacityOverride!=null&&(h.textOpacityOverride=c.textOpacityOverride);c.windowColor!=null&&(h.windowColor=c.windowColor);c.windowColorOverride!=null&&(h.windowColorOverride=c.windowColorOverride);c.windowOpacity!=null&&
(h.windowOpacity=c.windowOpacity);c.windowOpacityOverride!=null&&(h.windowOpacityOverride=c.windowOpacityOverride);return h};
g.J.eK=function(h,c){var t={};Object.assign(t,Ncy());Object.assign(t,h);j2p(this,t,c);this.player.F3("captionssettingschanged")};
g.J.yr=function(){!this.T&&this.loaded&&(g.xJ(this.q2,function(h,c){h.dispose();delete this.q2[c]},this),this.JV())};
g.J.lr=function(h,c){switch(h){case "fontSize":if(isNaN(c))break;h=g.J$(c,-2,4);this.eK({fontSizeIncrement:h});return h;case "reload":c&&!this.T&&yB(this,this.B,!0);break;case "stickyLoading":c!==void 0&&this.K.J&&(g.oN(this.K)?KL(this,!!c):nL(this,!!c));break;case "track":return X0I(this,c);case "tracklist":return this.X?g.jx(g.KK(this.X.B,!(!c||!c.includeAsr)),function(t){return g.Bo(t)}):[];
case "translationLanguages":return this.X?this.X.T.map(function(t){return Object.assign({},t)}):[];
case "sampleSubtitles":this.T||c===void 0||yNs(this,!!c);break;case "sampleSubtitlesCustomized":this.T||yNs(this,!!c,c);break;case "recommendedTranslationLanguages":return g.Ns();case "defaultTranslationSourceTrackIndices":return this.X?this.X.J:[]}};
g.J.getOptions=function(){var h="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.K.J&&h.push("stickyLoading");return h};
g.J.zn=function(){var h=this.B;if(this.Z.rf("captions")){if(this.K.L("html5_modify_caption_vss_logging")){var c;return(h=(c=this.videoData.qt)!=null?c:null)?{cc:g.xqZ(h)}:{}}if(h)return c=h.vssId,h.translationLanguage&&c&&(c="t"+c+"."+g.pZ(h)),{cc:c}}return{}};
g.J.lDB=function(){this.isSubtitlesOn()?(g.oN(this.K)?KL(this,!1):nL(this,!1),JeR(this),yB(this,null,!0)):this.uZ()};
g.J.uZ=function(){var h=oU(this)||!this.B?Nz(this,!0):this.B;h&&this.My(h.vssId,"m");this.isSubtitlesOn()||yB(this,oU(this)||!this.B?Nz(this,!0):this.B,!0)};
g.J.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!oU(this)};
g.J.uuM=function(){var h=oU(this);e2(this,h)?yB(this,this.getAudioTrack().X,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.iO()&&(this.J=!1,this.B=null,this.X&&(this.X.dispose(),this.X=null)),this.RM()&&(h?yB(this,Nz(this,!1),!1):this.load()))};
g.J.OB=function(h){h&&(this.XM={top:h.top,right:h.right,bottom:h.bottom,left:h.left,width:1-h.left-h.right,height:1-h.top-h.bottom},this.j.element.style.top=this.XM.top*100+"%",this.j.element.style.left=this.XM.left*100+"%",this.j.element.style.width=this.XM.width*100+"%",this.j.element.style.height=this.XM.height*100+"%",this.j.element.style.position="absolute",h=UV6(this))&&(this.j.element.style.width=h.width+"px",this.j.element.style.height=h.height+"px")};
g.J.onVideoDataChange=function(h,c){h==="newdata"&&(this.videoData=c,this.loaded&&this.unload(),this.J=!1,this.B=null,this.X&&(this.X.dispose(),this.X=null,this.player.F3("captionschanged",{})),this.RM()&&this.load())};
g.J.getAudioTrack=function(){return this.player.getAudioTrack()};
g.J.MCM=function(){var h=this.Z.Vl();h&&!h.Ht()&&h.H_();this.Z.isFullscreen()?(this.T=this.bB=!0,this.loaded&&this.KN()):(this.bB=this.K.controlsType==="3",this.T=dqI(this));yB(this,this.B)};
g.J.a5=function(){var h,c,t,p=(h=this.videoData.getPlayerResponse())==null?void 0:(c=h.captions)==null?void 0:(t=c.playerCaptionsTracklistRenderer)==null?void 0:t.openTranscriptCommand;p&&this.player.Wt("innertubeCommand",p)};
g.J.P8=function(h,c,t){var p=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,u="";h&&(u=h.vssId,u=u.replace(p,""));var q="";h&&h.getId()&&(q=h.getId()||"");h&&h.getXtags()&&(h=h.getXtags(),h=h.replace(p,""),q=q.concat(";"+h));this.Z.P8(c?u:"",c?q:"",t)};
g.J.My=function(h,c){h=(h||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");h.length>0&&this.Z.My(h,c)};g.lB("captions",Tcz);})(_yt_player);
