(function(g){var window=this;'use strict';var f2e=function(h){var c,t,p;return h==null?void 0:(c=h.playerOverlays)==null?void 0:(t=c.playerOverlayRenderer)==null?void 0:(p=t.autoplay)==null?void 0:p.playerOverlayAutoplayRenderer},jE=function(h){var c=h.Z.J8(!0,h.Z.isFullscreen());
g.fq(h.container.element,"ytp-autonav-endscreen-small-mode",h.Ms(c));g.fq(h.container.element,"ytp-autonav-endscreen-is-premium",!!h.suggestion&&!!h.suggestion.fcs);g.fq(h.Z.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!h.Z.lm());g.fq(h.Z.getRootNode(),"countdown-running",h.EP());g.fq(h.container.element,"ytp-player-content",h.Z.lm());g.wI(h.overlay.element,{width:c.width+"px"});if(!h.EP()){h.Z.lm()?Rf6(h,Math.round(JXs(h)/1E3)):Rf6(h);c=!!h.suggestion&&!!h.suggestion.XJ;var t=h.Z.lm()||
!c;g.fq(h.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!t&&c);g.fq(h.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",t&&!c);h.B.zt(h.Z.lm());g.fq(h.element,"ytp-enable-w2w-color-transitions",l2e(h))}},JXs=function(h){if(h.Z.isFullscreen()){var c;
h=(c=h.Z.getVideoData())==null?void 0:c.Ey;return h===-1||h===void 0?8E3:h}return h.Z.Lh()>=0?h.Z.Lh():g.Ti(h.Z.N().experiments,"autoplay_time")||1E4},Ch=function(h){IH.call(this,h,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.Q({D:"div",G:"ytp-suggestion-panel",V:[{D:"div",TM:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Bt:"Plus de vid\u00e9os"}]});this.j=new g.Q({D:"div",G:"ytp-suggestions-container"});this.videos=[];this.U=null;this.T=this.C=!1;this.B=new Y4(this.player);g.Z(this,this.B);this.B.DM(this.element);h.getVideoData().tU?this.X=this.B:(this.X=new bu(h),g.z1(this.player,this.X.element,4),g.Z(this,this.X));this.overlay=new g.Q({D:"div",
G:"ytp-autonav-overlay-cancelled-state"});g.Z(this,this.overlay);this.overlay.DM(this.element);this.Y=new g.dD(this);g.Z(this,this.Y);g.Z(this,this.table);this.table.DM(this.element);this.table.show();g.Z(this,this.j);this.j.DM(this.table.element);this.hide()},NPT=function(h){h.player.DP("endscreen");
var c=h.player.getVideoData();c=new g.et(Math.max((c.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var t=new g.et(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});h.player.bX([c,t])},TPs=function(h){var c=JXs(h),t=Math,p=t.min;
var u=h.U?Date.now()-h.U:0;t=p.call(t,u,c);Rf6(h,Math.ceil((c-t)/1E3));c-t<=500&&h.EP()?h.select(!0):h.EP()&&h.Y.start()},XBA=function(h){IH.call(this,h,"videowall-endscreen");
var c=this;this.Z=h;this.stills=[];this.U=this.videoData=null;this.Y=this.C=!1;this.j=null;g.iq(this.element,"modern-videowall-endscreen");this.B=new g.dD(this);g.Z(this,this.B);this.T=new g.SF(function(){g.iq(c.element,"ytp-show-tiles")},0);
g.Z(this,this.T);this.table=new g.JI({D:"div",G:"ytp-modern-endscreen-content"});g.Z(this,this.table);this.table.DM(this.element);h.getVideoData().tU?this.X=new Y4(h,!0):this.X=new bu(h);g.Z(this,this.X);g.z1(this.player,this.X.element,4);h.createClientVe(this.element,this,158789);this.hide()},iqI=function(h,c){h.Wt("onAutonavCoundownStarted",c)},UB1=function(h,c){c=WNs(h,c);
var t=Math,p=t.min;var u=(0,g.lZ)()-h.B;t=p.call(t,u,c);c=c===0?1:Math.min(t/c,1);h.T.setAttribute("stroke-dashoffset",""+-211*(c+1));c>=1&&h.EP()&&h.api.getPresentingPlayerType()!==3?h.select(!0):h.EP()&&h.X.start()},k4=function(h){var c=h.N(),t=c.Y;
g.Q.call(this,{D:"a",G:"ytp-autonav-suggestion-card",W:{href:"{{url}}",target:t?c.M2:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{D:"div",TM:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],W:{style:"{{background}}"},V:[{D:"div",W:{"aria-label":"{{timestamp}}"},TM:["ytp-autonav-timestamp"],Bt:"{{duration}}"},{D:"div",TM:["ytp-autonav-live-stamp"],Bt:"En direct"},
{D:"div",TM:["ytp-autonav-upcoming-stamp"],Bt:"\u00c0 venir"},{D:"div",G:"ytp-autonav-list-overlay",V:[{D:"div",G:"ytp-autonav-mix-text",Bt:"Mix"},{D:"div",G:"ytp-autonav-mix-icon"}]}]},{D:"div",TM:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Bt:"{{title}}"},{D:"div",TM:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Bt:"{{author}}"},{D:"div",TM:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Bt:"{{views_and_publish_time}}"}]});this.Z=
h;this.suggestion=null;this.X=t;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},GG=function(h){var c=h.lm();
c!==h.C&&(h.C=c,Oqq(h.player))},IH=function(h,c){g.Q.call(this,{D:"div",
TM:["html5-endscreen","ytp-player-content",c||"base-endscreen"]});this.created=!1;this.player=h},Dk=function(h){IH.call(this,h,"videowall-endscreen");
var c=this;this.Z=h;this.U=0;this.stills=[];this.Y=this.videoData=null;this.T=this.j=!1;this.J=null;this.B=new g.dD(this);g.Z(this,this.B);this.C=new g.SF(function(){g.iq(c.element,"ytp-show-tiles")},0);
g.Z(this,this.C);var t=new g.Q({D:"button",TM:["ytp-button","ytp-endscreen-previous"],W:{"aria-label":"Pr\u00e9c\u00e9dente"},V:[g.mS()]});g.Z(this,t);t.DM(this.element);t.listen("click",this.Lx,this);this.table=new g.JI({D:"div",G:"ytp-endscreen-content"});g.Z(this,this.table);this.table.DM(this.element);t=new g.Q({D:"button",TM:["ytp-button","ytp-endscreen-next"],W:{"aria-label":"Suivante"},V:[g.R8()]});g.Z(this,t);t.DM(this.element);t.listen("click",this.Zv,this);h.getVideoData().tU?this.X=new Y4(h,
!0):this.X=new bu(h);g.Z(this,this.X);g.z1(this.player,this.X.element,4);h.createClientVe(this.element,this,158789);this.hide()},rX6=function(h){var c=h.player.getVideoData();
if(!c||h.X===c.u2&&h.B===c.tU)return!1;h.X=c.u2;h.B=c.tU;return!0},KNI=function(h,c){g.Q.call(this,{D:"button",
TM:["ytp-watch-on-youtube-button","ytp-button"],Bt:"{{content}}"});this.Z=h;this.buttonType=this.buttonType=c;this.Ze();this.buttonType===2&&g.iq(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.Ze);this.zt(!0)},bu=function(h){g.Q.call(this,{D:"div",
TM:["ytp-upnext","ytp-player-content"],W:{"aria-label":"{{aria_label}}"},V:[{D:"div",G:"ytp-cued-thumbnail-overlay-image",W:{style:"{{background}}"}},{D:"span",G:"ytp-upnext-top",V:[{D:"span",G:"ytp-upnext-header",Bt:"\u00c0 suivre"},{D:"span",G:"ytp-upnext-title",Bt:"{{title}}"},{D:"span",G:"ytp-upnext-author",Bt:"{{author}}"}]},{D:"a",G:"ytp-upnext-autoplay-icon",W:{role:"button",href:"{{url}}","aria-label":"Lire la vid\u00e9o suivante"},V:[{D:"svg",W:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},V:[{D:"circle",G:"ytp-svg-autoplay-circle",W:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",G:"ytp-svg-autoplay-ring",W:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",G:"ytp-svg-fill",W:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",G:"ytp-upnext-bottom",V:[{D:"span",G:"ytp-upnext-cancel"},{D:"span",G:"ytp-upnext-paused",
Bt:"La lecture automatique est d\u00e9sactiv\u00e9e"}]}]});this.api=h;this.cancelButton=null;this.T=this.Yk("ytp-svg-autoplay-ring");this.U=this.notification=this.X=this.suggestion=null;this.Y=new g.SF(this.dN,5E3,this);this.B=0;var c=this.Yk("ytp-upnext-cancel");this.cancelButton=new g.Q({D:"button",TM:["ytp-upnext-cancel-button","ytp-button"],W:{tabindex:"0","aria-label":"Annuler la lecture automatique"},Bt:"Annuler"});g.Z(this,this.cancelButton);this.cancelButton.listen("click",this.Dv,this);this.cancelButton.DM(c);
this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.Z(this,this.Y);this.api.createClientVe(this.element,this,18788);c=this.Yk("ytp-upnext-autoplay-icon");this.S(c,"click",this.T5);this.api.createClientVe(c,this,115130);this.hY();this.S(h,"autonavvisibility",this.hY);this.S(h,"mdxnowautoplaying",this.sO1);this.S(h,"mdxautoplaycanceled",this.Xms);g.fq(this.element,"ytp-upnext-mobile",this.api.N().B)},Y4=function(h,c){c=c===void 0?!1:c;
g.Q.call(this,{D:"div",G:"ytp-autonav-endscreen-countdown-overlay"});var t=this;this.C=c;this.cancelCommand=this.T=void 0;this.U=0;this.container=new g.Q({D:"div",G:"ytp-autonav-endscreen-countdown-container"});g.Z(this,this.container);this.container.DM(this.element);c=h.N();var p=c.Y;this.Z=h;this.suggestion=null;this.onVideoDataChange("newdata",this.Z.getVideoData());this.S(h,"videodatachange",this.onVideoDataChange);this.X=new g.Q({D:"div",G:"ytp-autonav-endscreen-upnext-container",W:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},V:[{D:"div",G:"ytp-autonav-endscreen-upnext-header"},{D:"div",G:"ytp-autonav-endscreen-upnext-alternative-header",Bt:"{{autoplayAlternativeHeader}}"},{D:"a",G:"ytp-autonav-endscreen-link-container",W:{href:"{{url}}",target:p?c.M2:""},V:[{D:"div",G:"ytp-autonav-endscreen-upnext-thumbnail",W:{style:"{{background}}"},V:[{D:"div",W:{"aria-label":"{{timestamp}}"},TM:["ytp-autonav-timestamp"],
Bt:"{{duration}}"},{D:"div",TM:["ytp-autonav-live-stamp"],Bt:"En direct"},{D:"div",TM:["ytp-autonav-upcoming-stamp"],Bt:"\u00c0 venir"}]},{D:"div",G:"ytp-autonav-endscreen-video-info",V:[{D:"div",G:"ytp-autonav-endscreen-premium-badge"},{D:"div",G:"ytp-autonav-endscreen-upnext-title",Bt:"{{title}}"},{D:"div",G:"ytp-autonav-endscreen-upnext-author",Bt:"{{author}}"},{D:"div",G:"ytp-autonav-view-and-date",Bt:"{{views_and_publish_time}}"},{D:"div",G:"ytp-autonav-author-and-view",Bt:"{{author_and_views}}"}]}]}]});
g.Z(this,this.X);this.X.DM(this.container.element);p||this.S(this.X.Yk("ytp-autonav-endscreen-link-container"),"click",this.uP);this.Z.createClientVe(this.container.element,this,115127);this.Z.createClientVe(this.X.Yk("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.Q({D:"div",G:"ytp-autonav-overlay"});g.Z(this,this.overlay);this.overlay.DM(this.container.element);this.B=new g.Q({D:"div",G:"ytp-autonav-endscreen-button-container"});g.Z(this,this.B);this.B.DM(this.container.element);
this.cancelButton=new g.Q({D:"button",TM:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",c.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],W:{"aria-label":"Annuler la lecture automatique"},Bt:"Annuler"});g.Z(this,this.cancelButton);this.cancelButton.DM(this.B.element);this.cancelButton.listen("click",this.u8,this);this.Z.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.Q({D:"a",TM:["ytp-autonav-endscreen-upnext-button",
"ytp-autonav-endscreen-upnext-play-button",c.L("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],W:{href:"{{url}}",role:"button","aria-label":"Lire la vid\u00e9o suivante"},Bt:"Regarder"});g.Z(this,this.playButton);this.playButton.DM(this.B.element);this.playButton.listen("click",this.uP,this);this.Z.createServerVe(this.playButton.element,this.playButton,!0);(c=this.Z.getVideoData())&&o1e(this,c);this.Y=new g.SF(function(){TPs(t)},500);
g.Z(this,this.Y);this.lP();this.S(h,"autonavvisibility",this.lP);this.Z.L("web_autonav_color_transition")&&(this.S(h,"autonavchange",this.l8),this.S(h,"onAutonavCoundownStarted",this.hhM))},zfz=function(h){IH.call(this,h,"subscribecard-endscreen");
this.X=new g.Q({D:"div",G:"ytp-subscribe-card",V:[{D:"img",G:"ytp-author-image",W:{src:"{{profilePicture}}"}},{D:"div",G:"ytp-subscribe-card-right",V:[{D:"div",G:"ytp-author-name",Bt:"{{author}}"},{D:"div",G:"html5-subscribe-button-container"}]}]});g.Z(this,this.X);this.X.DM(this.element);var c=h.getVideoData();this.subscribeButton=new g.gp("S'abonner",null,"Se d\u00e9sabonner",null,!0,!1,c.XC,c.subscribed,"trailer-endscreen",null,h,!1);g.Z(this,this.subscribeButton);this.subscribeButton.DM(this.X.Yk("html5-subscribe-button-container"));
this.S(h,"videodatachange",this.Sb);this.Sb();this.hide()},mU=function(h){var c=h.N(),t=g.DQ||g.mF?{style:"will-change: opacity"}:void 0,p=c.Y,u=["ytp-videowall-still"];
c.B&&u.push("ytp-videowall-show-text");g.Q.call(this,{D:"a",TM:u,W:{href:"{{url}}",target:p?c.M2:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},V:[{D:"div",G:"ytp-videowall-still-image",W:{style:"{{background}}"}},{D:"span",G:"ytp-videowall-still-info",W:{"aria-hidden":"true"},V:[{D:"span",G:"ytp-videowall-still-info-bg",V:[{D:"span",G:"ytp-videowall-still-info-content",W:t,V:[{D:"span",G:"ytp-videowall-still-info-title",Bt:"{{title}}"},
{D:"span",G:"ytp-videowall-still-info-author",Bt:"{{author_and_views}}"},{D:"span",G:"ytp-videowall-still-info-live",Bt:"En direct"},{D:"span",G:"ytp-videowall-still-info-duration",Bt:"{{duration}}"}]}]}]},{D:"span",TM:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},V:[{D:"span",G:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",G:"ytp-videowall-still-listlabel-length",V:[" (",{D:"span",Bt:"{{playlist_length}}"},")"]}]},{D:"span",TM:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],W:{"aria-hidden":"true"},V:[{D:"span",G:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{D:"span",G:"ytp-videowall-still-listlabel-length",Bt:" (50+)"}]}]});this.suggestion=null;this.B=p;this.api=h;this.X=new g.dD(this);g.Z(this,this.X);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.X.S(h,"videodatachange",this.onVideoDataChange);h.createServerVe(this.element,this);this.onVideoDataChange()},fh=function(h){return g.VO(h.player)&&h.sx()&&
!h.U},RH=function(h){var c=h.lm();
c!==h.T&&(h.T=c,Oqq(h.player),h.T?(h.B!==h.X&&h.B.hide(),h.table.hide()):(h.B!==h.X&&h.B.show(),h.table.show()))},Hqm=function(h){g.dy.call(this,h);
var c=this;this.endScreen=null;this.X=this.B=this.U=!1;this.listeners=new g.dD(this);g.Z(this,this.listeners);var t=h.N();h.isEmbedsShortsMode()?this.endScreen=new Js(h):wBq(h)?(this.U=!0,rX6(this),this.X?this.endScreen=new Ch(h):t.L("delhi_modern_endscreen")?this.endScreen=new XBA(h):this.endScreen=new Dk(h)):t.im?this.endScreen=new zfz(h):this.endScreen=new IH(h);g.Z(this,this.endScreen);g.z1(h,this.endScreen.element,4);NPT(this);this.listeners.S(h,"videodatachange",this.onVideoDataChange,this);
this.listeners.S(h,g.GD("endscreen"),function(p){c.onCueRangeEnter(p)});
this.listeners.S(h,g.tL("endscreen"),function(p){c.onCueRangeExit(p)})},Rf6=function(h,c){c=c===void 0?-1:c;
h=h.X.Yk("ytp-autonav-endscreen-upnext-header");g.So(h);if(c>=0){c=String(c);var t="Prochaine vid\u00e9o dans $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],p="Prochaine vid\u00e9o dans $SECONDS".indexOf(t);if(p>=0){h.appendChild(g.YQ("Prochaine vid\u00e9o dans $SECONDS".slice(0,p)));var u=g.Cl("span");g.VA(u,"ytp-autonav-endscreen-upnext-header-countdown-number");g.sp(u,c);h.appendChild(u);h.appendChild(g.YQ("Prochaine vid\u00e9o dans $SECONDS".slice(p+t.length)));return}}g.sp(h,"\u00c0 suivre")},
o1e=function(h,c){c=c.getWatchNextResponse();
var t,p;c=(t=f2e(c))==null?void 0:(p=t.nextButton)==null?void 0:p.buttonRenderer;h.T=c==null?void 0:c.navigationEndpoint;t=c==null?void 0:c.trackingParams;h.playButton&&t&&h.Z.setTrackingParams(h.playButton.element,t)},wBq=function(h){h=h.N();
return h.mL&&!h.im&&!h.disableOrganicUi},lu=function(h){var c=h.lm();
c!==h.j&&(h.j=c,Oqq(h.player))},NZ=function(h){return g.VO(h.player)&&h.sx()&&!h.Y},WNs=function(h,c){if(c)return c;
if(h.api.isFullscreen()){var t;h=(t=h.api.getVideoData())==null?void 0:t.Ey;return h===-1||h===void 0?8E3:h}return h.api.Lh()>=0?h.api.Lh():g.Ti(h.api.N().experiments,"autoplay_time")||1E4},Js=function(h){IH.call(this,h,"watch-again-on-youtube-endscreen");
this.watchButton=new KNI(h,1);g.Z(this,this.watchButton);this.watchButton.DM(this.element);g.q1r(h)&&(this.X=new g.JB(h),g.Z(this,this.X),this.B=new g.Q({D:"div",TM:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],W:{tabIndex:"-1"},V:[this.X]}),g.Z(this,this.B),this.X.DM(this.B.element),this.B.DM(this.element));h.createClientVe(this.element,this,156914);this.hide()},l2e=function(h){var c;
return!((c=h.Z.getVideoData())==null||!c.watchToWatchTransitionRenderer)},Oqq=function(h){h.publish("autonavvisibility")};
g.yA.prototype.Lh=g.tc(6,function(){return this.app.Lh()});
g.Lf.prototype.Lh=g.tc(5,function(){return this.getVideoData().rN});
g.n4.prototype.eg=g.tc(4,function(h){this.A1().eg(h)});
g.UK.prototype.eg=g.tc(3,function(h){this.DH!==h&&(this.DH=h,this.Mz())});
g.L(k4,g.Q);k4.prototype.select=function(){this.Z.Xg(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.c_||void 0)&&this.Z.logClick(this.element)};
k4.prototype.onClick=function(h){g.kj(h,this.Z,this.X,this.suggestion.sessionData||void 0)&&this.select()};
k4.prototype.onKeyPress=function(h){switch(h.keyCode){case 13:case 32:h.defaultPrevented||(this.select(),h.preventDefault())}};g.L(Y4,g.Q);g.J=Y4.prototype;g.J.dK=function(h){this.suggestion!==h&&(this.suggestion=h,g.wW(this.X,h),this.playButton.updateValue("url",this.suggestion.N6()),jE(this))};
g.J.EP=function(){return this.U>0};
g.J.Mx=function(){this.EP()||(this.U=Date.now(),TPs(this),iqI(this.Z,JXs(this)),g.fq(this.Z.getRootNode(),"countdown-running",this.EP()))};
g.J.GB=function(){this.uK();TPs(this);var h=this.X.Yk("ytp-autonav-endscreen-upnext-header");h&&g.sp(h,"\u00c0 suivre")};
g.J.uK=function(){this.EP()&&(this.Y.stop(),this.U=0)};
g.J.select=function(h){this.Z.nextVideo(!1,h===void 0?!1:h);this.uK()};
g.J.uP=function(h){g.kj(h,this.Z)&&(h.currentTarget===this.playButton.element?this.Z.logClick(this.playButton.element):h.currentTarget===this.X.Yk("ytp-autonav-endscreen-link-container")&&(h=this.X.Yk("ytp-autonav-endscreen-link-container"),this.Z.logVisibility(h,!0),this.Z.logClick(h)),this.T?(this.Z.Wt("innertubeCommand",this.T),this.uK()):this.select())};
g.J.u8=function(){this.Z.logClick(this.cancelButton.element);g.k5(this.Z,!0);this.cancelCommand&&this.Z.Wt("innertubeCommand",this.cancelCommand)};
g.J.onVideoDataChange=function(h,c){o1e(this,c);h=c.getWatchNextResponse();var t,p;h=(t=f2e(h))==null?void 0:(p=t.cancelButton)==null?void 0:p.buttonRenderer;this.cancelCommand=h==null?void 0:h.command};
g.J.hhM=function(h){if(l2e(this)){var c=this.Z.getVideoData().watchToWatchTransitionRenderer,t=c==null?void 0:c.fromColorPaletteDark;c=c==null?void 0:c.toColorPaletteDark;if(t&&c){var p=this.element;p.style.setProperty("--w2w-start-background-color",g.pD(t.surgeColor));p.style.setProperty("--w2w-start-primary-text-color",g.pD(t.primaryTitleColor));p.style.setProperty("--w2w-start-secondary-text-color",g.pD(t.secondaryTitleColor));p.style.setProperty("--w2w-end-background-color",g.pD(c.surgeColor));
p.style.setProperty("--w2w-end-primary-text-color",g.pD(c.primaryTitleColor));p.style.setProperty("--w2w-end-secondary-text-color",g.pD(c.secondaryTitleColor));p.style.setProperty("--w2w-animation-duration",h+"ms")}g.fq(this.element,"ytp-w2w-animate",!0)}};
g.J.l8=function(h){this.Z.L("web_autonav_color_transition")&&h!==2&&g.fq(this.element,"ytp-w2w-animate",!1)};
g.J.lP=function(){var h=this.Z.lm();this.C&&this.Fu!==h&&this.zt(h);jE(this);this.Z.logVisibility(this.container.element,h);this.Z.logVisibility(this.cancelButton.element,h);this.Z.logVisibility(this.X.Yk("ytp-autonav-endscreen-link-container"),h);this.Z.logVisibility(this.playButton.element,h)};
g.J.Ms=function(h){return h.width<400||h.height<459};g.L(IH,g.Q);g.J=IH.prototype;g.J.create=function(){this.created=!0};
g.J.destroy=function(){this.created=!1};
g.J.sx=function(){return!1};
g.J.lm=function(){return!1};
g.J.zl=function(){return!1};g.L(bu,g.Q);g.J=bu.prototype;g.J.dN=function(){this.notification&&(this.Y.stop(),this.C3(this.U),this.U=null,this.notification.close(),this.notification=null)};
g.J.dK=function(h){this.suggestion=h;g.wW(this,h,"hqdefault.jpg")};
g.J.hY=function(){this.zt(this.api.lm());this.api.logVisibility(this.element,this.api.lm());this.api.logVisibility(this.Yk("ytp-upnext-autoplay-icon"),this.api.lm());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.lm())};
g.J.keB=function(){window.focus();this.dN()};
g.J.Mx=function(h){var c=this;this.EP()||(g.BB("a11y-announce","\u00c0 suivre "+this.suggestion.title),this.B=(0,g.lZ)(),this.X=new g.SF(function(){UB1(c,h)},25),UB1(this,h),iqI(this.api,WNs(this,h)));
g.NP(this.element,"ytp-upnext-autoplay-paused")};
g.J.hide=function(){g.Q.prototype.hide.call(this)};
g.J.EP=function(){return!!this.X};
g.J.GB=function(){this.uK();this.B=(0,g.lZ)();UB1(this);g.iq(this.element,"ytp-upnext-autoplay-paused")};
g.J.uK=function(){this.EP()&&(this.X.dispose(),this.X=null)};
g.J.select=function(h){h=h===void 0?!1:h;if(this.api.N().L("autonav_notifications")&&h&&window.Notification&&typeof document.hasFocus==="function"){var c=Notification.permission;c==="default"?Notification.requestPermission():c!=="granted"||document.hasFocus()||(this.dN(),this.notification=new Notification("\u00c0 suivre",{body:this.suggestion.title,icon:this.suggestion.jT()}),this.U=this.S(this.notification,"click",this.keB),this.Y.start())}this.uK();this.api.nextVideo(!1,h)};
g.J.T5=function(h){!g.vH(this.cancelButton.element,h.target)&&g.kj(h,this.api)&&(this.api.lm()&&this.api.logClick(this.Yk("ytp-upnext-autoplay-icon")),this.select())};
g.J.Dv=function(){this.api.lm()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.k5(this.api,!0)};
g.J.sO1=function(h){this.api.getPresentingPlayerType();this.show();this.Mx(h)};
g.J.Xms=function(){this.api.getPresentingPlayerType();this.uK();this.hide()};
g.J.FM=function(){this.uK();this.dN();g.Q.prototype.FM.call(this)};g.L(Ch,IH);g.J=Ch.prototype;g.J.create=function(){IH.prototype.create.call(this);this.Y.S(this.player,"appresize",this.cY);this.Y.S(this.player,"onVideoAreaChange",this.cY);this.Y.S(this.player,"videodatachange",this.onVideoDataChange);this.Y.S(this.player,"autonavchange",this.Dm);this.Y.S(this.player,"onAutonavCancelled",this.y7);this.onVideoDataChange()};
g.J.show=function(){IH.prototype.show.call(this);(this.C||this.U&&this.U!==this.videoData.clientPlaybackNonce)&&g.k5(this.player,!1);g.VO(this.player)&&this.sx()&&!this.U?(RH(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.X.select(!0):this.X.Mx():this.videoData.autonavState===3&&this.X.GB()):(g.k5(this.player,!0),RH(this));this.cY()};
g.J.hide=function(){IH.prototype.hide.call(this);this.X.GB();RH(this)};
g.J.cY=function(){var h=this.player.J8(!0,this.player.isFullscreen());RH(this);jE(this.B);g.fq(this.element,"ytp-autonav-cancelled-small-mode",this.Ms(h));g.fq(this.element,"ytp-autonav-cancelled-tiny-mode",this.Za(h));g.fq(this.element,"ytp-autonav-cancelled-mini-mode",h.width<=400||h.height<=360);this.overlay&&g.wI(this.overlay.element,{width:h.width+"px"});if(!this.T)for(h=0;h<this.videos.length;h++)g.fq(this.videos[h].element,"ytp-suggestion-card-with-margin",h%2===1)};
g.J.onVideoDataChange=function(){var h=this.player.getVideoData();if(this.videoData!==h&&h){this.videoData=h;h=this.videoData.suggestions;var c=g.C0(this.videoData);c&&(this.X.dK(c),this.X!==this.B&&this.B.dK(c));if(h&&h.length)for(c=0;c<QQz.length;++c){var t=QQz[c];if(h&&h[t]){this.videos[c]=new k4(this.player);var p=this.videos[c];t=h[t];p.suggestion!==t&&(p.suggestion=t,g.wW(p,t));g.Z(this,this.videos[c]);this.videos[c].DM(this.j.element)}}this.cY()}};
g.J.Dm=function(h){h===1?(this.C=!1,this.U=this.videoData.clientPlaybackNonce,this.X.uK(),this.Fu&&this.cY()):(this.C=!0,this.lm()&&(h===2?this.X.Mx():h===3&&this.X.GB()))};
g.J.y7=function(h){h?this.Dm(1):(this.U=null,this.C=!1)};
g.J.sx=function(){return this.videoData.autonavState!==1};
g.J.Ms=function(h){return(h.width<910||h.height<459)&&!this.Za(h)&&!(h.width<=400||h.height<=360)};
g.J.Za=function(h){return h.width<800&&!(h.width<=400||h.height<=360)};
g.J.lm=function(){return this.Fu&&g.VO(this.player)&&this.sx()&&!this.U};
var QQz=[1,3,2,4];g.L(XBA,IH);g.J=XBA.prototype;g.J.create=function(){IH.prototype.create.call(this);var h=this.player.getVideoData();h&&(this.videoData=h);this.pz();this.B.S(this.player,"appresize",this.pz);this.B.S(this.player,"onVideoAreaChange",this.pz);this.B.S(this.player,"videodatachange",this.onVideoDataChange);this.B.S(this.player,"autonavchange",this.R5);this.B.S(this.player,"onAutonavCancelled",this.Oo);h=this.videoData.autonavState;h!==this.j&&this.R5(h);this.B.S(this.element,"transitionend",this.mE)};
g.J.destroy=function(){g.T7(this.B);g.iB(this.stills);this.stills=[];IH.prototype.destroy.call(this);g.NP(this.element,"ytp-show-tiles");this.T.stop();this.j=this.videoData.autonavState};
g.J.sx=function(){return this.videoData.autonavState!==1};
g.J.show=function(){var h=this.Fu;IH.prototype.show.call(this);g.NP(this.element,"ytp-show-tiles");this.player.N().B?g.M8(this.T):this.T.start();(this.Y||this.U&&this.U!==this.videoData.clientPlaybackNonce)&&g.k5(this.player,!1);fh(this)?(GG(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.X.select(!0):this.X.Mx():this.videoData.autonavState===3&&this.X.GB()):(g.k5(this.player,!0),GG(this));h!==this.Fu&&this.player.logVisibility(this.element,!0)};
g.J.hide=function(){var h=this.Fu;IH.prototype.hide.call(this);this.X.GB();GG(this);h!==this.Fu&&this.player.logVisibility(this.element,!1)};
g.J.mE=function(h){h.target===this.element&&this.pz()};
g.J.pz=function(){var h,c,t,p;var u=((h=this.videoData)==null?0:(c=h.suggestions)==null?0:c.length)?(t=this.videoData)==null?void 0:t.suggestions:[(p=this.videoData)==null?void 0:g.C0(p)];if(u.length){c=this.Z.J8(!0,this.Z.isFullscreen());h=Math.floor((c.width-64+16)/(g.J$(c.width*.27,250,450)+16));c=Math.min(3,Math.floor((c.height-64)/((c.width-64-(h-1)*16)/h*.5625+70)));g.Zn(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.iq(this.element,"ytp-modern-endscreen-limit-rows-"+c);g.fq(this.element,"ytp-modern-endscreen-single-item",h===1);g.fq(this.element,"ytp-modern-endscreen-row-0",c===0);h=this.table.element;h.ariaLive="polite";this.X.dK(g.C0(this.videoData));this.X instanceof Y4&&jE(this.X);g.fq(this.element,"ytp-endscreen-takeover",fh(this));GG(this);c=0;h.ariaBusy="true";t=u.length;for(p=0;p<t;p++){var q=p%t,I=this.stills[p];I||(I=new g.C$(this.player),this.stills[p]=I,h.appendChild(I.element));g.WZy(I,u[q]);c++}this.stills.length=
c}};
g.J.onVideoDataChange=function(){var h=this.player.getVideoData(1);this.videoData!==h&&(h!=null&&g.C0(h)?(this.videoData=h,this.pz()):this.player.s8("missg",{vid:(h==null?void 0:h.videoId)||"",cpn:(h==null?void 0:h.clientPlaybackNonce)||""}))};
g.J.zl=function(){return this.X.EP()};
g.J.R5=function(h){h===1?(this.Y=!1,this.U=this.videoData.clientPlaybackNonce,this.X.uK(),this.Fu&&this.pz()):(this.Y=!0,this.Fu&&fh(this)&&(h===2?this.X.Mx():h===3&&this.X.GB()))};
g.J.Oo=function(h){if(h){for(h=0;h<this.stills.length;h++)this.Z.logVisibility(this.stills[h].element,!0);this.R5(1)}else this.U=null,this.Y=!1;this.pz()};
g.J.lm=function(){return this.Fu&&fh(this)};g.L(zfz,IH);zfz.prototype.Sb=function(){var h=this.player.getVideoData();this.X.update({profilePicture:h.profilePicture,author:h.author});this.subscribeButton.channelId=h.XC;var c=this.subscribeButton;h.subscribed?c.X():c.B()};g.L(mU,g.Q);mU.prototype.select=function(){this.api.Xg(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.c_||void 0)&&this.api.logClick(this.element)};
mU.prototype.onClick=function(h){if(g.CK(this.api.N())&&this.api.L("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var c=this.suggestion.N6(),t={};g.EZ(this.api,t);c=g.GR(c,t);g.nt(c,this.api,h)}else g.kj(h,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
mU.prototype.onKeyPress=function(h){switch(h.keyCode){case 13:case 32:h.defaultPrevented||(this.select(),h.preventDefault())}};
mU.prototype.onVideoDataChange=function(){var h=this.api.getVideoData(),c=this.api.N();this.B=h.Ql?!1:c.Y};g.L(Dk,IH);g.J=Dk.prototype;g.J.create=function(){IH.prototype.create.call(this);var h=this.player.getVideoData();h&&(this.videoData=h);this.lw();this.B.S(this.player,"appresize",this.lw);this.B.S(this.player,"onVideoAreaChange",this.lw);this.B.S(this.player,"videodatachange",this.onVideoDataChange);this.B.S(this.player,"autonavchange",this.Kf);this.B.S(this.player,"onAutonavCancelled",this.Hv);h=this.videoData.autonavState;h!==this.J&&this.Kf(h);this.B.S(this.element,"transitionend",this.Cx)};
g.J.destroy=function(){g.T7(this.B);g.iB(this.stills);this.stills=[];IH.prototype.destroy.call(this);g.NP(this.element,"ytp-show-tiles");this.C.stop();this.J=this.videoData.autonavState};
g.J.sx=function(){return this.videoData.autonavState!==1};
g.J.show=function(){var h=this.Fu;IH.prototype.show.call(this);g.NP(this.element,"ytp-show-tiles");this.player.N().B?g.M8(this.C):this.C.start();(this.T||this.Y&&this.Y!==this.videoData.clientPlaybackNonce)&&g.k5(this.player,!1);NZ(this)?(lu(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.X.select(!0):this.X.Mx():this.videoData.autonavState===3&&this.X.GB()):(g.k5(this.player,!0),lu(this));h!==this.Fu&&this.player.logVisibility(this.element,!0)};
g.J.hide=function(){var h=this.Fu;IH.prototype.hide.call(this);this.X.GB();lu(this);h!==this.Fu&&this.player.logVisibility(this.element,!1)};
g.J.Cx=function(h){h.target===this.element&&this.lw()};
g.J.lw=function(){var h,c,t,p;var u=((h=this.videoData)==null?0:(c=h.suggestions)==null?0:c.length)?(t=this.videoData)==null?void 0:t.suggestions:[(p=this.videoData)==null?void 0:g.C0(p)];if(u.length){g.iq(this.element,"ytp-endscreen-paginate");var q=this.Z.J8(!0,this.Z.isFullscreen());if(h=g.Vp(this.Z))h=h.mU()?48:32,q.width-=h*2;var I=q.width/q.height;p=96/54;c=h=2;var b=Math.max(q.width/96,2),C=Math.max(q.height/54,2);t=u.length;var k=t*4;for(k-=4;k>0&&(h<b||c<C);){var G=h/2,D=c/2,m=h<=b-2&&k>=
D*4,f=c<=C-2&&k>=G*4;if((G+1)/D*p/I>I/(G/(D+1)*p)&&f)k-=G*4,c+=2;else if(m)k-=D*4,h+=2;else if(f)k-=G*4,c+=2;else break}p=!1;k>=12&&t*4-k<=6&&(c>=4||h>=4)&&(p=!0);k=h*96;b=c*54;I=k/b<I?q.height/b:q.width/k;I=Math.min(I,2);k=Math.floor(Math.min(q.width,k*I));b=Math.floor(Math.min(q.height,b*I));q=this.table.element;q.ariaLive="polite";g.JQ(q,k,b);g.wI(q,{marginLeft:k/-2+"px",marginTop:b/-2+"px"});this.X.dK(g.C0(this.videoData));this.X instanceof Y4&&jE(this.X);g.fq(this.element,"ytp-endscreen-takeover",
NZ(this));lu(this);k+=4;b+=4;I=0;q.ariaBusy="true";for(C=0;C<h;C++)for(G=0;G<c;G++)if(D=I,f=0,p&&C>=h-2&&G>=c-2?f=1:G%2===0&&C%2===0&&(G<2&&C<2?G===0&&C===0&&(f=2):f=2),D=g.OM(D+this.U,t),f!==0){m=this.stills[I];m||(m=new mU(this.player),this.stills[I]=m,q.appendChild(m.element));var R=Math.floor(b*G/c),X=Math.floor(k*C/h),O=Math.floor(b*(G+f)/c)-R-4,w=Math.floor(k*(C+f)/h)-X-4;g.Wq(m.element,X,R);g.JQ(m.element,w,O);g.wI(m.element,"transitionDelay",(G+C)/20+"s");g.fq(m.element,"ytp-videowall-still-mini",
f===1);g.fq(m.element,"ytp-videowall-still-large",f>2);f=Math.max(w,O);g.fq(m.element,"ytp-videowall-still-round-large",f>=256);g.fq(m.element,"ytp-videowall-still-round-medium",f>96&&f<256);g.fq(m.element,"ytp-videowall-still-round-small",f<=96);D=u[D];m.suggestion!==D&&(m.suggestion=D,f=m.api.N(),R=g.gR(m.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.wW(m,D,R),g.CK(f)&&!m.api.L("web_player_log_click_before_generating_ve_conversion_params")&&(f=D.N6(),R={},g.k8(m.api,"addEmbedsConversionTrackingParams",
[R]),f=g.GR(f,R),m.updateValue("url",f)),(D=(D=D.sessionData)&&D.itct)&&m.api.setTrackingParams(m.element,D));I++}q.ariaBusy="false";g.fq(this.element,"ytp-endscreen-paginate",I<t);for(u=this.stills.length-1;u>=I;u--)h=this.stills[u],g.t9(h.element),g.xz(h);this.stills.length=I}};
g.J.onVideoDataChange=function(){var h=this.player.getVideoData(1);this.videoData!==h&&(h!=null&&g.C0(h)?(this.U=0,this.videoData=h,this.lw()):this.player.s8("missg",{vid:(h==null?void 0:h.videoId)||"",cpn:(h==null?void 0:h.clientPlaybackNonce)||""}))};
g.J.Zv=function(){this.U+=this.stills.length;this.lw()};
g.J.Lx=function(){this.U-=this.stills.length;this.lw()};
g.J.zl=function(){return this.X.EP()};
g.J.Kf=function(h){h===1?(this.T=!1,this.Y=this.videoData.clientPlaybackNonce,this.X.uK(),this.Fu&&this.lw()):(this.T=!0,this.Fu&&NZ(this)&&(h===2?this.X.Mx():h===3&&this.X.GB()))};
g.J.Hv=function(h){if(h){for(h=0;h<this.stills.length;h++)this.Z.logVisibility(this.stills[h].element,!0);this.Kf(1)}else this.Y=null,this.T=!1;this.lw()};
g.J.lm=function(){return this.Fu&&NZ(this)};g.L(KNI,g.Q);g.J=KNI.prototype;g.J.Ze=function(){switch(this.buttonType){case 1:var h="Regarder \u00e0 nouveau sur YouTube";var c=156915;break;case 2:h="Continuer \u00e0 regarder sur YouTube";c=156942;break;default:h="Continuer \u00e0 regarder sur YouTube",c=156942}this.update({content:h});this.Z.hasVe(this.element)&&this.Z.destroyVe(this.element);this.Z.createClientVe(this.element,this,c)};
g.J.onClick=function(h){this.Z.L("web_player_log_click_before_generating_ve_conversion_params")&&this.Z.logClick(this.element);g.nt(this.getVideoUrl(),this.Z,h);this.Z.L("web_player_log_click_before_generating_ve_conversion_params")||this.Z.logClick(this.element)};
g.J.getVideoUrl=function(){var h=!0;switch(this.buttonType){case 1:h=!0;break;case 2:h=!1}h=this.Z.getVideoUrl(h,!1,!1,!0);var c=this.Z.N();if(g.CK(c)){var t={};g.CK(c)&&g.k8(this.Z,"addEmbedsConversionTrackingParams",[t]);h=g.GR(h,t)}return h};
g.J.logVisibility=function(){this.Z.logVisibility(this.element,this.Fu&&this.M2)};
g.J.show=function(){g.Q.prototype.show.call(this);this.logVisibility()};
g.J.hide=function(){g.Q.prototype.hide.call(this);this.logVisibility()};
g.J.rJ=function(h){g.Q.prototype.rJ.call(this,h);this.logVisibility()};g.L(Js,IH);Js.prototype.hasSuggestions=function(){var h;return(h=this.X)==null?void 0:h.hasSuggestions()};
Js.prototype.show=function(){if(this.player.getPlayerState()!==3){IH.prototype.show.call(this);var h=this.B;if(h){var c=this.X.hasSuggestions();g.fq(this.element,"ytp-shorts-branded-ui",c);c?h.show():h.hide()}var t;(t=g.Vp(this.player))==null||t.eg(!0);this.player.logVisibility(this.element,!0);this.watchButton.rJ(!0)}};
Js.prototype.hide=function(){IH.prototype.hide.call(this);var h;(h=g.Vp(this.player))==null||h.eg(!1);this.player.logVisibility(this.element,!1);this.watchButton.rJ(!1)};g.L(Hqm,g.dy);g.J=Hqm.prototype;g.J.RM=function(){var h=this.player.getVideoData(),c=h.mutedAutoplay&&(h.limitedPlaybackDurationInSeconds>0||h.endSeconds>0||h.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!c)return!0;var t;var p=!!((h==null?0:g.C0(h))||(h==null?0:(t=h.suggestions)==null?0:t.length));p=!wBq(this.player)||p;h=h.XE;t=this.player.b_();return p&&!h&&!t&&!c};
g.J.lm=function(){return this.endScreen.lm()};
g.J.R4=function(){return this.lm()?this.endScreen.zl():!1};
g.J.FM=function(){this.player.DP("endscreen");g.dy.prototype.FM.call(this)};
g.J.load=function(){var h=this.player.getVideoData();var c=h.transitionEndpointAtEndOfStream;if(c&&c.videoId){var t=this.player.DT().Rz.get("heartbeat"),p=g.C0(h);!p||c.videoId!==p.videoId||h.Z$?(this.player.Xg(c.videoId,void 0,void 0,!0,!0,c),t&&t.nQ("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),h=!0):h=!1}else h=!1;h||(g.dy.prototype.load.call(this),this.endScreen.show())};
g.J.unload=function(){g.dy.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.J.onCueRangeEnter=function(h){this.RM()&&(this.endScreen.created||this.endScreen.create(),h.getId()==="load"&&this.load())};
g.J.onCueRangeExit=function(h){h.getId()==="load"&&this.loaded&&this.unload()};
g.J.onVideoDataChange=function(){NPT(this);this.U&&rX6(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.X?this.endScreen=new Ch(this.player):this.endScreen=new Dk(this.player),g.Z(this,this.endScreen),g.z1(this.player,this.endScreen.element,4))};g.lB("endscreen",Hqm);})(_yt_player);
